#ifndef __CONST_AR__
#define __CONST_AR__

#define SIZE_PAGE_SERIAL_DATAFLASH_AR                   264
#define NUMBER_PAGES_INTO_SERIAL_DATAFLASH_AR           32768


#define GLOBAL_ADDRESS_TABLE_AR 0x0
#define SIZE_TABLE_AR           85800

#define GLOBAL_ADDRESS_DATA_AR  (GLOBAL_ADDRESS_TABLE_AR + SIZE_TABLE_AR)

#define MIN_ADDRESS_DATA_AR_AREA                0x0
#define MAX_ADDRESS_DATA_AR_AREA                (SIZE_PAGE_SERIAL_DATAFLASH_AR*NUMBER_PAGES_INTO_SERIAL_DATAFLASH_AR - SIZE_TABLE_AR - 1)

#define NUMBER_DATA_BLOCKS                      85649

#define DATA_BLOCK_EMPTY                        0xff

enum _task_ar
{
  TASK_START_READ_TABLE_DATA = 0,
  TASK_READING_TABLE_DATA,
  
  TASK_START_WRITE_TABLE_DATA,
  TASK_WRITING_TABLE_DATA,

  TASK_START_READ_DATA,
  TASK_READING_DATA,
  
  TASK_START_WRITE_DATA,
  TASK_WRITING_DATA,
};

#endif
