#include "gui_const.h"

#include "const_global_mal.h"

#include "diagnostyka_mal.h"
#include "EEPROM_RTC_DataFlash.h"

#include "const_menu_mal.h"
#include "pickup_interval.h"
#include "General_titles_panel.h"
#include "DZ_panel.h"
#include "MTZ_panel.h"
#include "Umin_panel.h"
#include "Umax_panel.h"
#include "TZNP_panel.h"
#include "ZOP_panel.h"
#include "APV_panel.h"
#include "UROV_panel.h"
#include "CB_panel.h"
#include "dialogs_mal.h"
#include "Settings_panel.h"
#include "Comm_panel.h"
#include "Modbus_panel.h"
#include "Net_panel.h"
#include "Transformer_panel.h"
#include "Resurs_panel.h"
#include "Clock_panel.h"
#include "LCD_Settings_panel.h"
#include "main_menu.h "
#include "TM_panel.h"
#include "Diagnostics_panel.h"
#include "About_panel.h"
#include "Registrators_panel.h"

#include "const_global_ZigBee.h"


