#ifndef __GLOBAL_VARIABLES_MAL_H
#define __GLOBAL_VARIABLES_MAL_H

#include "external_variables_for_global_mal.h"

//DDR2 __root unsigned int test_DDR2_variable[5] = {0x01020304, 0x05060708, 0x090A0B0C, 0x0D0E0F10, 0x11121314};

unsigned int tick_for_1s = 0;
unsigned int tick_for_2s = 0;
unsigned int tick_for_3s = 0;

//Змінні для роботи emWin у режтмі мультипортовості
int _PendingBuffer = -1;

__CURRENT_EKRAN current_ekran;
int position_in_current_level_menu[MAX_LEVEL_MENU];
int previous_level_in_current_level_menu[MAX_LEVEL_MENU];
unsigned int command_menu = 0;
unsigned int executed_action_after_press_ctrl = false;

int position_in_level_1_menu_DZ[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_DZ_delay[2] = {0, 0};
int position_in_level_1_menu_MTZ[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_Umin[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_Umax[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_TZNP[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_ZOP[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_APV[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_UROV[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_CB[MAX_PAGES_PROTECTION_SDC];
int position_in_level_1_menu_Transformer = 0;
int position_in_level_1_menu_Modbus = 0;
int position_in_level_1_menu_Net = 0;
int position_in_level_1_menu_Clock = 0;
int position_in_level_1_menu_TM[2] = {0, 0};
int position_in_level_1_menu_Diagnostics[3] = {0, 0, 0};

const TITLE MODE = {TITLE_EDITION_UKR, TITLE_EDITION_RUS, TITLE_EDITION_ENG};
const TITLE ERROR_MES = {TITLE_ERROR_UKR, TITLE_ERROR_RUS, TITLE_ERROR_ENG};
const TITLE NONE = {"Нема", "Нет", "None"};

const TITLE title_from = {TITLE_FROM_UKR, TITLE_FROM_RUS, TITLE_FROM_ENG};

const TITLE ON_OFF[2] = 
{
  {TITLE_OFF_UKR, TITLE_OFF_RUS, TITLE_OFF_ENG},
  {TITLE_ON_UKR , TITLE_ON_RUS , TITLE_ON_ENG }
};
const TITLE SELECTOR[3] = 
{
  {TITLE_SELECTOR_0_UKR, TITLE_SELECTOR_0_RUS, TITLE_SELECTOR_0_ENG},
  {TITLE_SELECTOR_1_UKR, TITLE_SELECTOR_1_RUS, TITLE_SELECTOR_1_ENG},
  {TITLE_SELECTOR_2_UKR, TITLE_SELECTOR_2_RUS, TITLE_SELECTOR_2_ENG}
};
const TITLE UMIN_UMAX_TYPE[2] = 
{
  {TITLE_UMIN_UMAX_TYPE_0_UKR, TITLE_UMIN_UMAX_TYPE_0_RUS, TITLE_UMIN_UMAX_TYPE_0_ENG},
  {TITLE_UMIN_UMAX_TYPE_1_UKR, TITLE_UMIN_UMAX_TYPE_1_RUS, TITLE_UMIN_UMAX_TYPE_1_ENG}
};
const TITLE UMIN_UMAX_VOLTAGE[2] = 
{
  {TITLE_UMIN_UMAX_VOLTAGE_0_UKR, TITLE_UMIN_UMAX_VOLTAGE_0_RUS, TITLE_UMIN_UMAX_VOLTAGE_0_ENG},
  {TITLE_UMIN_UMAX_VOLTAGE_1_UKR, TITLE_UMIN_UMAX_VOLTAGE_1_RUS, TITLE_UMIN_UMAX_VOLTAGE_1_ENG}
};
const TITLE NAPRJAMOK[2] = 
{
  {TITLE_NAPRJAMOK_NAZAD_UKR , TITLE_NAPRJAMOK_NAZAD_RUS , TITLE_NAPRJAMOK_NAZAD_ENG },
  {TITLE_NAPRJAMOK_VPERED_UKR, TITLE_NAPRJAMOK_VPERED_RUS, TITLE_NAPRJAMOK_VPERED_ENG}
};
const TITLE PHASES[3] = {
                         {"A", "A", "A"},
                         {"B", "B", "B"},
                         {"C", "C", "C"}
                        };
const TITLE NAPRJAMOK_1[2] = 
{
  {TITLE_NAPRJAMOK_ZVOROTNJA_UKR, TITLE_NAPRJAMOK_ZVOROTNJA_RUS, TITLE_NAPRJAMOK_ZVOROTNJA_ENG},
  {TITLE_NAPRJAMOK_PRJAMA_UKR   , TITLE_NAPRJAMOK_PRJAMA_RUS   , TITLE_NAPRJAMOK_PRJAMA_ENG   }
};

const TITLE ENTER_ESC[2] = 
{
  {TITLE_ENTER_UKR, TITLE_ENTER_RUS, TITLE_ENTER_ENG},
  {TITLE_ESC_UKR  , TITLE_ESC_RUS  , TITLE_ESC_ENG  }
};

const char empty_string[] = "";
const char gradus[] = "°";
const TITLE MEASURES[TOTAL_AMOUNT_OF_MEASURES] = 
{
  {TITLE_A_UKR               , TITLE_A_RUS               , TITLE_A_ENG               },
  {TITLE_kA_UKR              , TITLE_kA_RUS              , TITLE_kA_ENG              },
  {TITLE_V_UKR               , TITLE_V_RUS               , TITLE_V_ENG               },
  {TITLE_S_UKR               , TITLE_S_RUS               , TITLE_S_ENG               },
  {TITLE_DEGREE_DIV_S_UKR    , TITLE_DEGREE_DIV_S_RUS    , TITLE_DEGREE_DIV_S_ENG    },
  {TITLE_RESISTANCE_UKR      , TITLE_RESISTANCE_RUS      , TITLE_RESISTANCE_ENG      },
  {TITLE_RESISTANCE_DIV_S_UKR, TITLE_RESISTANCE_DIV_S_RUS, TITLE_RESISTANCE_DIV_S_ENG}
};

WM_HWIN Dialog_confirmation_FrameWin = WM_UNATTACHED, DC_Text, DC_ENTER_Button, DC_ESC_Button;
const TITLE Dialog_confirmation_title = {TITLE_DIALOGS_CONFIRMATION_UKR, TITLE_DIALOGS_CONFIRMATION_RUS, TITLE_DIALOGS_CONFIRMATION_ENG};
TITLE Dialog_confirmation_message = {"", "", ""};

WM_HWIN Dialog_confirmation_level_2_FrameWin = WM_UNATTACHED, DC_level_2_Text, DC_ENTER_level_2_Button, DC_ESC_level_2_Button;
TITLE Dialog_confirmation_level_2_message = {"", "", ""};

WM_HWIN Dialog_error_FrameWin = WM_UNATTACHED, DE_Text, DE_ENTER_Button, DE_ESC_Button;
const TITLE Dialog_error_title = {TITLE_DIALOGS_ERROR_UKR, TITLE_DIALOGS_ERROR_RUS, TITLE_DIALOGS_ERROR_ENG};
TITLE Dialog_error_message = {"", "", ""};

WM_HWIN Dialog_error_level_2_FrameWin = WM_UNATTACHED, DE_level_2_Text, DE_ENTER_level_2_Button, DE_ESC_level_2_Button;
TITLE Dialog_error_level_2_message = {"", "", ""};

WM_HWIN Unreliable_error_FrameWin = WM_UNATTACHED, UE_Text, UE_ESC_Button;
WM_HWIN Unreliable_error_level_2_FrameWin = WM_UNATTACHED, UE_level_2_Text, UE_ESC_level_2_Button;
const TITLE Unreliable_error_title = {TITLE_UNRELIABLE_ERROR_UKR, TITLE_UNRELIABLE_ERROR_RUS, TITLE_UNRELIABLE_ERROR_ENG};
const TITLE Unreliable_error_message = {UNRELIABLE_SETTINGS_MSG_UKR, UNRELIABLE_SETTINGS_MSG_RUS, UNRELIABLE_SETTINGS_MSG_ENG};


WM_HWIN Dialog_password_FrameWin = WM_UNATTACHED, DP_Edit, DP_ENTER_Button, DP_ESC_Button;
WM_HWIN Dialog_password_level_2_FrameWin = WM_UNATTACHED, DP_level_2_Edit, DP_ENTER_level_2_Button, DP_ESC_level_2_Button;
const TITLE Dialog_password_title[] = 
{
  {TITLE_DIALOGS_PASSWORD_UKR      , TITLE_DIALOGS_PASSWORD_RUS      , TITLE_DIALOGS_PASSWORD_ENG      },
  {TITLE_DIALOGS_PASSWORD_OLD_1_UKR, TITLE_DIALOGS_PASSWORD_OLD_1_RUS, TITLE_DIALOGS_PASSWORD_OLD_1_ENG},
  {TITLE_DIALOGS_PASSWORD_OLD_2_UKR, TITLE_DIALOGS_PASSWORD_OLD_2_RUS, TITLE_DIALOGS_PASSWORD_OLD_2_ENG},
  {TITLE_DIALOGS_PASSWORD_NEW_1_UKR, TITLE_DIALOGS_PASSWORD_NEW_1_RUS, TITLE_DIALOGS_PASSWORD_NEW_1_ENG},
  {TITLE_DIALOGS_PASSWORD_NEW_2_UKR, TITLE_DIALOGS_PASSWORD_NEW_2_RUS, TITLE_DIALOGS_PASSWORD_NEW_2_ENG}
};
char  typed_password[MAX_NUMBER_SYMBOLS_IN_PASSWORD + 1] = "";
char  typed_password_level_2[MAX_NUMBER_SYMBOLS_IN_PASSWORD + 1] = "";
int cursor_position_dp = 0;
int cursor_position_dp_level_2 = 0;
unsigned int command_word_for_change_password = 0;

const LANG_ITEM _MultiPage_groups_Items[AMOUNT_SERIES_PPSPM_SETTINGS + 1] = {
  { {TITLE_1_GROUP_UKR  , TITLE_1_GROUP_RUS  , TITLE_1_GROUP_ENG  } , {EXPL_1_GROUP_UKR  , EXPL_1_GROUP_RUS  , EXPL_1_GROUP_ENG  } },
  { {TITLE_2_GROUP_UKR  , TITLE_2_GROUP_RUS  , TITLE_2_GROUP_ENG  } , {EXPL_2_GROUP_UKR  , EXPL_2_GROUP_RUS  , EXPL_2_GROUP_ENG  } },
  { {TITLE_3_GROUP_UKR  , TITLE_3_GROUP_RUS  , TITLE_3_GROUP_ENG  } , {EXPL_3_GROUP_UKR  , EXPL_3_GROUP_RUS  , EXPL_3_GROUP_ENG  } },
  { {TITLE_4_GROUP_UKR  , TITLE_4_GROUP_RUS  , TITLE_4_GROUP_ENG  } , {EXPL_4_GROUP_UKR  , EXPL_4_GROUP_RUS  , EXPL_4_GROUP_ENG  } },
  { {TITLE_ALL_GROUP_UKR, TITLE_ALL_GROUP_RUS, TITLE_ALL_GROUP_ENG} , {EXPL_ALL_GROUP_UKR, EXPL_ALL_GROUP_RUS, EXPL_ALL_GROUP_ENG} }
};

const LANG_ITEM _MultiPage_type_info_Items[MAX_PAGES_PROTECTION_SDC] = {
  { {TITLE_PICKUPS_UKR, TITLE_PICKUPS_RUS, TITLE_PICKUPS_ENG} , {EXPL_PICKUPS_UKR, EXPL_PICKUPS_RUS, EXPL_PICKUPS_ENG} },
  { {TITLE_DELAYS_UKR , TITLE_DELAYS_RUS , TITLE_DELAYS_ENG } , {EXPL_DELAYS_UKR , EXPL_DELAYS_RUS , EXPL_DELAYS_ENG } },
  { {TITLE_CONTROL_UKR, TITLE_CONTROL_RUS, TITLE_CONTROL_ENG} , {EXPL_CONTROL_UKR, EXPL_CONTROL_RUS, EXPL_CONTROL_ENG} }
};

WM_HWIN MTZ_FrameWin = WM_UNATTACHED, MTZ_MultiPage_groups, MTZ_Window_group, MTZ_MultiPage_type_info, MTZ_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_MTZ_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_MTZ = 0, _y_cbDelay_MTZ = 0, _y_cbControl_MTZ = 0;
WM_HWIN MTZ_Pickup_t[MAX_NUMBER_PICKUP_MTZ], MTZ_Pickup_v[MAX_NUMBER_PICKUP_MTZ], MTZ_Pickup_m[MAX_NUMBER_PICKUP_MTZ];
WM_HWIN MTZ_Delay_t[MAX_NUMBER_DELAY_MTZ], MTZ_Delay_v[MAX_NUMBER_DELAY_MTZ], MTZ_Delay_m[MAX_NUMBER_DELAY_MTZ];
WM_HWIN MTZ_State_t[MAX_NUMBER_CTRL_MTZ], MTZ_State_v[MAX_NUMBER_CTRL_MTZ];
const unsigned short int nalashtuvannja_MTZ[MAX_KILKIST_STUPENIV_MTZ + 1] = {MAX_NUMBER_CTRL_MTZ1, MAX_NUMBER_CTRL_MTZ2, MAX_NUMBER_CTRL_MTZ3, MAX_NUMBER_CTRL_MTZ4, MAX_NUMBER_CTRL_MTZ5, MAX_NUMBER_CTRL_MTZ_G};

const TITLE MTZ_panel_title = {TITLE_MTZ_PANEL_UKR, TITLE_MTZ_PANEL_RUS, TITLE_MTZ_PANEL_ENG};

const TITLE MTZ_Pickup_title[MAX_NUMBER_PICKUP_MTZ] = 
{
  {TITLE_MTZ1_PICKUP0_UKR, TITLE_MTZ1_PICKUP0_RUS, TITLE_MTZ1_PICKUP0_ENG},
  {TITLE_MTZ1_PICKUP1_UKR, TITLE_MTZ1_PICKUP1_RUS, TITLE_MTZ1_PICKUP1_ENG},
  {TITLE_MTZ1_PICKUP2_UKR, TITLE_MTZ1_PICKUP2_RUS, TITLE_MTZ1_PICKUP2_ENG},
  {TITLE_MTZ1_PICKUP3_UKR, TITLE_MTZ1_PICKUP3_RUS, TITLE_MTZ1_PICKUP3_ENG},
  {TITLE_MTZ1_PICKUP4_UKR, TITLE_MTZ1_PICKUP4_RUS, TITLE_MTZ1_PICKUP4_ENG},
  {TITLE_MTZ1_PICKUP5_UKR, TITLE_MTZ1_PICKUP5_RUS, TITLE_MTZ1_PICKUP5_ENG},

  {TITLE_MTZ2_PICKUP0_UKR, TITLE_MTZ2_PICKUP0_RUS, TITLE_MTZ2_PICKUP0_ENG},
  {TITLE_MTZ2_PICKUP1_UKR, TITLE_MTZ2_PICKUP1_RUS, TITLE_MTZ2_PICKUP1_ENG},
  {TITLE_MTZ2_PICKUP2_UKR, TITLE_MTZ2_PICKUP2_RUS, TITLE_MTZ2_PICKUP2_ENG},
  {TITLE_MTZ2_PICKUP3_UKR, TITLE_MTZ2_PICKUP3_RUS, TITLE_MTZ2_PICKUP3_ENG},
  {TITLE_MTZ2_PICKUP4_UKR, TITLE_MTZ2_PICKUP4_RUS, TITLE_MTZ2_PICKUP4_ENG},
  {TITLE_MTZ2_PICKUP5_UKR, TITLE_MTZ2_PICKUP5_RUS, TITLE_MTZ2_PICKUP5_ENG},

  {TITLE_MTZ3_PICKUP0_UKR, TITLE_MTZ3_PICKUP0_RUS, TITLE_MTZ3_PICKUP0_ENG},
  {TITLE_MTZ3_PICKUP1_UKR, TITLE_MTZ3_PICKUP1_RUS, TITLE_MTZ3_PICKUP1_ENG},
  {TITLE_MTZ3_PICKUP2_UKR, TITLE_MTZ3_PICKUP2_RUS, TITLE_MTZ3_PICKUP2_ENG},
  {TITLE_MTZ3_PICKUP3_UKR, TITLE_MTZ3_PICKUP3_RUS, TITLE_MTZ3_PICKUP3_ENG},
  {TITLE_MTZ3_PICKUP4_UKR, TITLE_MTZ3_PICKUP4_RUS, TITLE_MTZ3_PICKUP4_ENG},
  {TITLE_MTZ3_PICKUP5_UKR, TITLE_MTZ3_PICKUP5_RUS, TITLE_MTZ3_PICKUP5_ENG},

  {TITLE_MTZ4_PICKUP0_UKR, TITLE_MTZ4_PICKUP0_RUS, TITLE_MTZ4_PICKUP0_ENG},
  {TITLE_MTZ4_PICKUP1_UKR, TITLE_MTZ4_PICKUP1_RUS, TITLE_MTZ4_PICKUP1_ENG},
  {TITLE_MTZ4_PICKUP2_UKR, TITLE_MTZ4_PICKUP2_RUS, TITLE_MTZ4_PICKUP2_ENG},
  {TITLE_MTZ4_PICKUP3_UKR, TITLE_MTZ4_PICKUP3_RUS, TITLE_MTZ4_PICKUP3_ENG},
  {TITLE_MTZ4_PICKUP4_UKR, TITLE_MTZ4_PICKUP4_RUS, TITLE_MTZ4_PICKUP4_ENG},
  {TITLE_MTZ4_PICKUP5_UKR, TITLE_MTZ4_PICKUP5_RUS, TITLE_MTZ4_PICKUP5_ENG},

  {TITLE_MTZ5_PICKUP0_UKR, TITLE_MTZ5_PICKUP0_RUS, TITLE_MTZ5_PICKUP0_ENG},
  {TITLE_MTZ5_PICKUP1_UKR, TITLE_MTZ5_PICKUP1_RUS, TITLE_MTZ5_PICKUP1_ENG},
  {TITLE_MTZ5_PICKUP2_UKR, TITLE_MTZ5_PICKUP2_RUS, TITLE_MTZ5_PICKUP2_ENG},
  {TITLE_MTZ5_PICKUP3_UKR, TITLE_MTZ5_PICKUP3_RUS, TITLE_MTZ5_PICKUP3_ENG},
  {TITLE_MTZ5_PICKUP4_UKR, TITLE_MTZ5_PICKUP4_RUS, TITLE_MTZ5_PICKUP4_ENG},
  {TITLE_MTZ5_PICKUP5_UKR, TITLE_MTZ5_PICKUP5_RUS, TITLE_MTZ5_PICKUP5_ENG}
};

const TITLE MTZ_Delay_title[MAX_NUMBER_DELAY_MTZ] = 
{
  {TITLE_MTZ1_DELAY0_UKR, TITLE_MTZ1_DELAY0_RUS, TITLE_MTZ1_DELAY0_ENG},
  {TITLE_MTZ1_DELAY1_UKR, TITLE_MTZ1_DELAY1_RUS, TITLE_MTZ1_DELAY1_ENG},
  {TITLE_MTZ1_DELAY2_UKR, TITLE_MTZ1_DELAY2_RUS, TITLE_MTZ1_DELAY2_ENG},
  {TITLE_MTZ1_DELAY3_UKR, TITLE_MTZ1_DELAY3_RUS, TITLE_MTZ1_DELAY3_ENG},

  {TITLE_MTZ2_DELAY0_UKR , TITLE_MTZ2_DELAY0_RUS , TITLE_MTZ2_DELAY0_ENG },
  {TITLE_MTZ2_DELAY1_UKR , TITLE_MTZ2_DELAY1_RUS , TITLE_MTZ2_DELAY1_ENG },
  {TITLE_MTZ2_DELAY2_UKR , TITLE_MTZ2_DELAY2_RUS , TITLE_MTZ2_DELAY2_ENG },
  {TITLE_MTZ2_DELAY3_UKR , TITLE_MTZ2_DELAY3_RUS , TITLE_MTZ2_DELAY3_ENG },
  {TITLE_MTZ2_DELAY4_UKR , TITLE_MTZ2_DELAY4_RUS , TITLE_MTZ2_DELAY4_ENG },
  {TITLE_MTZ2_DELAY5_UKR , TITLE_MTZ2_DELAY5_RUS , TITLE_MTZ2_DELAY5_ENG },
  {TITLE_MTZ2_DELAY6_UKR , TITLE_MTZ2_DELAY6_RUS , TITLE_MTZ2_DELAY6_ENG },
  {TITLE_MTZ2_DELAY7_UKR , TITLE_MTZ2_DELAY7_RUS , TITLE_MTZ2_DELAY7_ENG },
  {TITLE_MTZ2_DELAY8_UKR , TITLE_MTZ2_DELAY8_RUS , TITLE_MTZ2_DELAY8_ENG },
  {TITLE_MTZ2_DELAY9_UKR , TITLE_MTZ2_DELAY9_RUS , TITLE_MTZ2_DELAY9_ENG },
  {TITLE_MTZ2_DELAY10_UKR, TITLE_MTZ2_DELAY10_RUS, TITLE_MTZ2_DELAY10_ENG},
  {TITLE_MTZ2_DELAY11_UKR, TITLE_MTZ2_DELAY11_RUS, TITLE_MTZ2_DELAY11_ENG},
  {TITLE_MTZ2_DELAY12_UKR, TITLE_MTZ2_DELAY12_RUS, TITLE_MTZ2_DELAY12_ENG},
  {TITLE_MTZ2_DELAY13_UKR, TITLE_MTZ2_DELAY13_RUS, TITLE_MTZ2_DELAY13_ENG},
  {TITLE_MTZ2_DELAY14_UKR, TITLE_MTZ2_DELAY14_RUS, TITLE_MTZ2_DELAY14_ENG},
  {TITLE_MTZ2_DELAY15_UKR, TITLE_MTZ2_DELAY15_RUS, TITLE_MTZ2_DELAY15_ENG},
  {TITLE_MTZ2_DELAY16_UKR, TITLE_MTZ2_DELAY16_RUS, TITLE_MTZ2_DELAY16_ENG},

  {TITLE_MTZ3_DELAY0_UKR , TITLE_MTZ3_DELAY0_RUS , TITLE_MTZ3_DELAY0_ENG },
  {TITLE_MTZ3_DELAY1_UKR , TITLE_MTZ3_DELAY1_RUS , TITLE_MTZ3_DELAY1_ENG },
  {TITLE_MTZ3_DELAY2_UKR , TITLE_MTZ3_DELAY2_RUS , TITLE_MTZ3_DELAY2_ENG },
  {TITLE_MTZ3_DELAY3_UKR , TITLE_MTZ3_DELAY3_RUS , TITLE_MTZ3_DELAY3_ENG },
  {TITLE_MTZ3_DELAY4_UKR , TITLE_MTZ3_DELAY4_RUS , TITLE_MTZ3_DELAY4_ENG },
  {TITLE_MTZ3_DELAY5_UKR , TITLE_MTZ3_DELAY5_RUS , TITLE_MTZ3_DELAY5_ENG },
  {TITLE_MTZ3_DELAY6_UKR , TITLE_MTZ3_DELAY6_RUS , TITLE_MTZ3_DELAY6_ENG } ,
  {TITLE_MTZ3_DELAY7_UKR , TITLE_MTZ3_DELAY7_RUS , TITLE_MTZ3_DELAY7_ENG },
  {TITLE_MTZ3_DELAY8_UKR , TITLE_MTZ3_DELAY8_RUS , TITLE_MTZ3_DELAY8_ENG },
  {TITLE_MTZ3_DELAY9_UKR , TITLE_MTZ3_DELAY9_RUS , TITLE_MTZ3_DELAY9_ENG },
  {TITLE_MTZ3_DELAY10_UKR, TITLE_MTZ3_DELAY10_RUS, TITLE_MTZ3_DELAY10_ENG},
  {TITLE_MTZ3_DELAY11_UKR, TITLE_MTZ3_DELAY11_RUS, TITLE_MTZ3_DELAY11_ENG},
  {TITLE_MTZ3_DELAY12_UKR, TITLE_MTZ3_DELAY12_RUS, TITLE_MTZ3_DELAY12_ENG},
  {TITLE_MTZ3_DELAY13_UKR, TITLE_MTZ3_DELAY13_RUS, TITLE_MTZ3_DELAY13_ENG},
  {TITLE_MTZ3_DELAY14_UKR, TITLE_MTZ3_DELAY14_RUS, TITLE_MTZ3_DELAY14_ENG},
  {TITLE_MTZ3_DELAY15_UKR, TITLE_MTZ3_DELAY15_RUS, TITLE_MTZ3_DELAY15_ENG},
  {TITLE_MTZ3_DELAY16_UKR, TITLE_MTZ3_DELAY16_RUS, TITLE_MTZ3_DELAY16_ENG},

  {TITLE_MTZ4_DELAY0_UKR , TITLE_MTZ4_DELAY0_RUS , TITLE_MTZ4_DELAY0_ENG },
  {TITLE_MTZ4_DELAY1_UKR , TITLE_MTZ4_DELAY1_RUS , TITLE_MTZ4_DELAY1_ENG },
  {TITLE_MTZ4_DELAY2_UKR , TITLE_MTZ4_DELAY2_RUS , TITLE_MTZ4_DELAY2_ENG },
  {TITLE_MTZ4_DELAY3_UKR , TITLE_MTZ4_DELAY3_RUS , TITLE_MTZ4_DELAY3_ENG },
  {TITLE_MTZ4_DELAY4_UKR , TITLE_MTZ4_DELAY4_RUS , TITLE_MTZ4_DELAY4_ENG },
  {TITLE_MTZ4_DELAY5_UKR , TITLE_MTZ4_DELAY5_RUS , TITLE_MTZ4_DELAY5_ENG },
  {TITLE_MTZ4_DELAY6_UKR , TITLE_MTZ4_DELAY6_RUS , TITLE_MTZ4_DELAY6_ENG },
  {TITLE_MTZ4_DELAY7_UKR , TITLE_MTZ4_DELAY7_RUS , TITLE_MTZ4_DELAY7_ENG },
  {TITLE_MTZ4_DELAY8_UKR , TITLE_MTZ4_DELAY8_RUS , TITLE_MTZ4_DELAY8_ENG },
  {TITLE_MTZ4_DELAY9_UKR , TITLE_MTZ4_DELAY9_RUS , TITLE_MTZ4_DELAY9_ENG },
  {TITLE_MTZ4_DELAY10_UKR, TITLE_MTZ4_DELAY10_RUS, TITLE_MTZ4_DELAY10_ENG},
  {TITLE_MTZ4_DELAY11_UKR, TITLE_MTZ4_DELAY11_RUS, TITLE_MTZ4_DELAY11_ENG},
  {TITLE_MTZ4_DELAY12_UKR, TITLE_MTZ4_DELAY12_RUS, TITLE_MTZ4_DELAY12_ENG},
  {TITLE_MTZ4_DELAY13_UKR, TITLE_MTZ4_DELAY13_RUS, TITLE_MTZ4_DELAY13_ENG},
  {TITLE_MTZ4_DELAY14_UKR, TITLE_MTZ4_DELAY14_RUS, TITLE_MTZ4_DELAY14_ENG},
  {TITLE_MTZ4_DELAY15_UKR, TITLE_MTZ4_DELAY15_RUS, TITLE_MTZ4_DELAY15_ENG},
  {TITLE_MTZ4_DELAY16_UKR, TITLE_MTZ4_DELAY16_RUS, TITLE_MTZ4_DELAY16_ENG},

  {TITLE_MTZ5_DELAY0_UKR , TITLE_MTZ5_DELAY0_RUS , TITLE_MTZ5_DELAY0_ENG },
  {TITLE_MTZ5_DELAY1_UKR , TITLE_MTZ5_DELAY1_RUS , TITLE_MTZ5_DELAY1_ENG },
  {TITLE_MTZ5_DELAY2_UKR , TITLE_MTZ5_DELAY2_RUS , TITLE_MTZ5_DELAY2_ENG },
  {TITLE_MTZ5_DELAY3_UKR , TITLE_MTZ5_DELAY3_RUS , TITLE_MTZ5_DELAY3_ENG },
  {TITLE_MTZ5_DELAY4_UKR , TITLE_MTZ5_DELAY4_RUS , TITLE_MTZ5_DELAY4_ENG },
  {TITLE_MTZ5_DELAY5_UKR , TITLE_MTZ5_DELAY5_RUS , TITLE_MTZ5_DELAY5_ENG },
  {TITLE_MTZ5_DELAY6_UKR , TITLE_MTZ5_DELAY6_RUS , TITLE_MTZ5_DELAY6_ENG },
  {TITLE_MTZ5_DELAY7_UKR , TITLE_MTZ5_DELAY7_RUS , TITLE_MTZ5_DELAY7_ENG },
  {TITLE_MTZ5_DELAY8_UKR , TITLE_MTZ5_DELAY8_RUS , TITLE_MTZ5_DELAY8_ENG },
  {TITLE_MTZ5_DELAY9_UKR , TITLE_MTZ5_DELAY9_RUS , TITLE_MTZ5_DELAY9_ENG },
  {TITLE_MTZ5_DELAY10_UKR, TITLE_MTZ5_DELAY10_RUS, TITLE_MTZ5_DELAY10_ENG},
  {TITLE_MTZ5_DELAY11_UKR, TITLE_MTZ5_DELAY11_RUS, TITLE_MTZ5_DELAY11_ENG},
  {TITLE_MTZ5_DELAY12_UKR, TITLE_MTZ5_DELAY12_RUS, TITLE_MTZ5_DELAY12_ENG},
  {TITLE_MTZ5_DELAY13_UKR, TITLE_MTZ5_DELAY13_RUS, TITLE_MTZ5_DELAY13_ENG},
  {TITLE_MTZ5_DELAY14_UKR, TITLE_MTZ5_DELAY14_RUS, TITLE_MTZ5_DELAY14_ENG},
  {TITLE_MTZ5_DELAY15_UKR, TITLE_MTZ5_DELAY15_RUS, TITLE_MTZ5_DELAY15_ENG},
  {TITLE_MTZ5_DELAY16_UKR, TITLE_MTZ5_DELAY16_RUS, TITLE_MTZ5_DELAY16_ENG}
};
const TITLE MTZ_State_title[MAX_NUMBER_CTRL_MTZ] = 
{
  {TITLE_MTZ1_STATE0_UKR, TITLE_MTZ1_STATE0_RUS, TITLE_MTZ1_STATE0_ENG},
  {TITLE_MTZ1_STATE1_UKR, TITLE_MTZ1_STATE1_RUS, TITLE_MTZ1_STATE1_ENG},
  {TITLE_MTZ1_STATE2_UKR, TITLE_MTZ1_STATE2_RUS, TITLE_MTZ1_STATE2_ENG},
  {TITLE_MTZ1_STATE3_UKR, TITLE_MTZ1_STATE3_RUS, TITLE_MTZ1_STATE3_ENG},
  
  {TITLE_MTZ2_STATE0_UKR, TITLE_MTZ2_STATE0_RUS, TITLE_MTZ2_STATE0_ENG},
  {TITLE_MTZ2_STATE1_UKR, TITLE_MTZ2_STATE1_RUS, TITLE_MTZ2_STATE1_ENG},
  {TITLE_MTZ2_STATE2_UKR, TITLE_MTZ2_STATE2_RUS, TITLE_MTZ2_STATE2_ENG},
  {TITLE_MTZ2_STATE3_UKR, TITLE_MTZ2_STATE3_RUS, TITLE_MTZ2_STATE3_ENG},
  {TITLE_MTZ2_STATE4_UKR, TITLE_MTZ2_STATE4_RUS, TITLE_MTZ2_STATE4_ENG},
  {TITLE_MTZ2_STATE5_UKR, TITLE_MTZ2_STATE5_RUS, TITLE_MTZ2_STATE5_ENG},
  {TITLE_MTZ2_STATE6_UKR, TITLE_MTZ2_STATE6_RUS, TITLE_MTZ2_STATE6_ENG},
  
  {TITLE_MTZ3_STATE0_UKR, TITLE_MTZ3_STATE0_RUS, TITLE_MTZ3_STATE0_ENG},
  {TITLE_MTZ3_STATE1_UKR, TITLE_MTZ3_STATE1_RUS, TITLE_MTZ3_STATE1_ENG},
  {TITLE_MTZ3_STATE2_UKR, TITLE_MTZ3_STATE2_RUS, TITLE_MTZ3_STATE2_ENG},
  {TITLE_MTZ3_STATE3_UKR, TITLE_MTZ3_STATE3_RUS, TITLE_MTZ3_STATE3_ENG},
  {TITLE_MTZ3_STATE4_UKR, TITLE_MTZ3_STATE4_RUS, TITLE_MTZ3_STATE4_ENG},
  {TITLE_MTZ3_STATE5_UKR, TITLE_MTZ3_STATE5_RUS, TITLE_MTZ3_STATE5_ENG},
  {TITLE_MTZ3_STATE6_UKR, TITLE_MTZ3_STATE6_RUS, TITLE_MTZ3_STATE6_ENG},
  
  {TITLE_MTZ4_STATE0_UKR, TITLE_MTZ4_STATE0_RUS, TITLE_MTZ4_STATE0_ENG},
  {TITLE_MTZ4_STATE1_UKR, TITLE_MTZ4_STATE1_RUS, TITLE_MTZ4_STATE1_ENG},
  {TITLE_MTZ4_STATE2_UKR, TITLE_MTZ4_STATE2_RUS, TITLE_MTZ4_STATE2_ENG},
  {TITLE_MTZ4_STATE3_UKR, TITLE_MTZ4_STATE3_RUS, TITLE_MTZ4_STATE3_ENG},
  {TITLE_MTZ4_STATE4_UKR, TITLE_MTZ4_STATE4_RUS, TITLE_MTZ4_STATE4_ENG},
  {TITLE_MTZ4_STATE5_UKR, TITLE_MTZ4_STATE5_RUS, TITLE_MTZ4_STATE5_ENG},
  {TITLE_MTZ4_STATE6_UKR, TITLE_MTZ4_STATE6_RUS, TITLE_MTZ4_STATE6_ENG},
  
  {TITLE_MTZ5_STATE0_UKR, TITLE_MTZ5_STATE0_RUS, TITLE_MTZ5_STATE0_ENG},
  {TITLE_MTZ5_STATE1_UKR, TITLE_MTZ5_STATE1_RUS, TITLE_MTZ5_STATE1_ENG},
  {TITLE_MTZ5_STATE2_UKR, TITLE_MTZ5_STATE2_RUS, TITLE_MTZ5_STATE2_ENG},
  {TITLE_MTZ5_STATE3_UKR, TITLE_MTZ5_STATE3_RUS, TITLE_MTZ5_STATE3_ENG},
  {TITLE_MTZ5_STATE4_UKR, TITLE_MTZ5_STATE4_RUS, TITLE_MTZ5_STATE4_ENG},
  {TITLE_MTZ5_STATE5_UKR, TITLE_MTZ5_STATE5_RUS, TITLE_MTZ5_STATE5_ENG},
  {TITLE_MTZ5_STATE6_UKR, TITLE_MTZ5_STATE6_RUS, TITLE_MTZ5_STATE6_ENG},

  {TITLE_MTZ_STATE0_UKR, TITLE_MTZ_STATE0_RUS, TITLE_MTZ_STATE0_ENG}
};
int MTZ_select_group = 0;

WM_HWIN Umin_FrameWin = WM_UNATTACHED, Umin_MultiPage_groups, Umin_Window_group, Umin_MultiPage_type_info, Umin_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_Umin_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_Umin = 0, _y_cbDelay_Umin = 0, _y_cbControl_Umin = 0;
WM_HWIN Umin_Pickup_t[MAX_NUMBER_PICKUP_UMIN], Umin_Pickup_v[MAX_NUMBER_PICKUP_UMIN], Umin_Pickup_m[MAX_NUMBER_PICKUP_UMIN];
WM_HWIN Umin_Delay_t[MAX_NUMBER_DELAY_UMIN], Umin_Delay_v[MAX_NUMBER_DELAY_UMIN], Umin_Delay_m[MAX_NUMBER_DELAY_UMIN];
WM_HWIN Umin_State_t[MAX_NUMBER_CTRL_UMIN], Umin_State_v[MAX_NUMBER_CTRL_UMIN];
const unsigned short int nalashtuvannja_Umin[MAX_KILKIST_STUPENIV_UMIN + 1] = {MAX_NUMBER_CTRL_UMIN1, MAX_NUMBER_CTRL_UMIN2, MAX_NUMBER_CTRL_UMIN_G};

const TITLE Umin_panel_title = {TITLE_UMIN_PANEL_UKR, TITLE_UMIN_PANEL_RUS, TITLE_UMIN_PANEL_ENG};

const TITLE Umin_Pickup_title[MAX_NUMBER_PICKUP_UMIN] = 
{
  {TITLE_UMIN1_PICKUP0_UKR, TITLE_UMIN1_PICKUP0_RUS, TITLE_UMIN1_PICKUP0_ENG},
  {TITLE_UMIN1_PICKUP1_UKR, TITLE_UMIN1_PICKUP1_RUS, TITLE_UMIN1_PICKUP1_ENG},

  {TITLE_UMIN2_PICKUP0_UKR, TITLE_UMIN2_PICKUP0_RUS, TITLE_UMIN2_PICKUP0_ENG},
  {TITLE_UMIN2_PICKUP1_UKR, TITLE_UMIN2_PICKUP1_RUS, TITLE_UMIN2_PICKUP1_ENG}
};
const TITLE Umin_Delay_title[MAX_NUMBER_DELAY_UMIN] = 
{
  {TITLE_UMIN1_DELAY0_UKR, TITLE_UMIN1_DELAY0_RUS, TITLE_UMIN1_DELAY0_ENG},

  {TITLE_UMIN2_DELAY0_UKR, TITLE_UMIN2_DELAY0_RUS, TITLE_UMIN2_DELAY0_ENG},
};
const TITLE Umin_State_title[MAX_NUMBER_CTRL_UMIN] = 
{
  {TITLE_UMIN1_STATE0_UKR, TITLE_UMIN1_STATE0_RUS, TITLE_UMIN1_STATE0_ENG},
  {TITLE_UMIN1_STATE1_UKR, TITLE_UMIN1_STATE1_RUS, TITLE_UMIN1_STATE1_ENG},
  {TITLE_UMIN1_STATE2_UKR, TITLE_UMIN1_STATE2_RUS, TITLE_UMIN1_STATE2_ENG},
  {TITLE_UMIN1_STATE3_UKR, TITLE_UMIN1_STATE3_RUS, TITLE_UMIN1_STATE3_ENG},

  {TITLE_UMIN2_STATE0_UKR, TITLE_UMIN2_STATE0_RUS, TITLE_UMIN2_STATE0_ENG},
  {TITLE_UMIN2_STATE1_UKR, TITLE_UMIN2_STATE1_RUS, TITLE_UMIN2_STATE1_ENG},
  {TITLE_UMIN2_STATE2_UKR, TITLE_UMIN2_STATE2_RUS, TITLE_UMIN2_STATE2_ENG},
  {TITLE_UMIN2_STATE3_UKR, TITLE_UMIN2_STATE3_RUS, TITLE_UMIN2_STATE3_ENG},

  {TITLE_UMIN_STATE0_UKR , TITLE_UMIN_STATE0_RUS , TITLE_UMIN_STATE0_ENG }
};
int Umin_select_group = 0;

WM_HWIN Umax_FrameWin = WM_UNATTACHED, Umax_MultiPage_groups, Umax_Window_group, Umax_MultiPage_type_info, Umax_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_Umax_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_Umax = 0, _y_cbDelay_Umax = 0, _y_cbControl_Umax = 0;
WM_HWIN Umax_Pickup_t[MAX_NUMBER_PICKUP_UMAX], Umax_Pickup_v[MAX_NUMBER_PICKUP_UMAX], Umax_Pickup_m[MAX_NUMBER_PICKUP_UMAX];
WM_HWIN Umax_Delay_t[MAX_NUMBER_DELAY_UMAX], Umax_Delay_v[MAX_NUMBER_DELAY_UMAX], Umax_Delay_m[MAX_NUMBER_DELAY_UMAX];
WM_HWIN Umax_State_t[MAX_NUMBER_CTRL_UMAX], Umax_State_v[MAX_NUMBER_CTRL_UMAX];
const unsigned short int nalashtuvannja_Umax[MAX_KILKIST_STUPENIV_UMAX + 1] = {MAX_NUMBER_CTRL_UMAX1, MAX_NUMBER_CTRL_UMAX2, MAX_NUMBER_CTRL_UMAX_G};

const TITLE Umax_panel_title = {TITLE_UMAX_PANEL_UKR, TITLE_UMAX_PANEL_RUS, TITLE_UMAX_PANEL_ENG};

const TITLE Umax_Pickup_title[MAX_NUMBER_PICKUP_UMAX] = 
{
  {TITLE_UMAX1_PICKUP0_UKR, TITLE_UMAX1_PICKUP0_RUS, TITLE_UMAX1_PICKUP0_ENG},

  {TITLE_UMAX2_PICKUP0_UKR, TITLE_UMAX2_PICKUP0_RUS, TITLE_UMAX2_PICKUP0_ENG}
};
const TITLE Umax_Delay_title[MAX_NUMBER_DELAY_UMAX] = 
{
  {TITLE_UMAX1_DELAY0_UKR, TITLE_UMAX1_DELAY0_RUS, TITLE_UMAX1_DELAY0_ENG},

  {TITLE_UMAX2_DELAY0_UKR, TITLE_UMAX2_DELAY0_RUS, TITLE_UMAX2_DELAY0_ENG},
};
const TITLE Umax_State_title[MAX_NUMBER_CTRL_UMAX] = 
{
  {TITLE_UMAX1_STATE0_UKR, TITLE_UMAX1_STATE0_RUS, TITLE_UMAX1_STATE0_ENG},
  {TITLE_UMAX1_STATE1_UKR, TITLE_UMAX1_STATE1_RUS, TITLE_UMAX1_STATE1_ENG},

  {TITLE_UMAX2_STATE0_UKR, TITLE_UMAX2_STATE0_RUS, TITLE_UMAX2_STATE0_ENG},
  {TITLE_UMAX2_STATE1_UKR, TITLE_UMAX2_STATE1_RUS, TITLE_UMAX2_STATE1_ENG},

  {TITLE_UMAX_STATE0_UKR , TITLE_UMAX_STATE0_RUS , TITLE_UMAX_STATE0_ENG }
};
int Umax_select_group = 0;

WM_HWIN TZNP_FrameWin = WM_UNATTACHED, TZNP_MultiPage_groups, TZNP_Window_group, TZNP_MultiPage_type_info, TZNP_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_TZNP_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_TZNP = 0, _y_cbDelay_TZNP = 0, _y_cbControl_TZNP = 0;
WM_HWIN TZNP_Pickup_t[MAX_NUMBER_PICKUP_TZNP], TZNP_Pickup_v[MAX_NUMBER_PICKUP_TZNP], TZNP_Pickup_m[MAX_NUMBER_PICKUP_TZNP];
WM_HWIN TZNP_Delay_t[MAX_NUMBER_DELAY_TZNP], TZNP_Delay_v[MAX_NUMBER_DELAY_TZNP], TZNP_Delay_m[MAX_NUMBER_DELAY_TZNP];
WM_HWIN TZNP_State_t[MAX_NUMBER_CTRL_TZNP], TZNP_State_v[MAX_NUMBER_CTRL_TZNP];
const unsigned short int nalashtuvannja_TZNP[MAX_KILKIST_STUPENIV_TZNP + 1] = {MAX_NUMBER_CTRL_TZNP1, MAX_NUMBER_CTRL_TZNP2, MAX_NUMBER_CTRL_TZNP3, MAX_NUMBER_CTRL_TZNP4, MAX_NUMBER_CTRL_TZNP5, MAX_NUMBER_CTRL_TZNP_G};

const TITLE TZNP_panel_title = {TITLE_TZNP_PANEL_UKR, TITLE_TZNP_PANEL_RUS, TITLE_TZNP_PANEL_ENG};

const TITLE TZNP_Pickup_title[MAX_NUMBER_PICKUP_TZNP] = 
{
  {TITLE_TZNP1_PICKUP0_UKR, TITLE_TZNP1_PICKUP0_RUS, TITLE_TZNP1_PICKUP0_ENG},
  {TITLE_TZNP1_PICKUP1_UKR, TITLE_TZNP1_PICKUP1_RUS, TITLE_TZNP1_PICKUP1_ENG},
  {TITLE_TZNP1_PICKUP2_UKR, TITLE_TZNP1_PICKUP2_RUS, TITLE_TZNP1_PICKUP2_ENG},

  {TITLE_TZNP2_PICKUP0_UKR, TITLE_TZNP2_PICKUP0_RUS, TITLE_TZNP1_PICKUP0_ENG},
  {TITLE_TZNP2_PICKUP1_UKR, TITLE_TZNP2_PICKUP1_RUS, TITLE_TZNP1_PICKUP1_ENG},
  {TITLE_TZNP2_PICKUP2_UKR, TITLE_TZNP2_PICKUP2_RUS, TITLE_TZNP1_PICKUP2_ENG},

  {TITLE_TZNP3_PICKUP0_UKR, TITLE_TZNP3_PICKUP0_RUS, TITLE_TZNP3_PICKUP0_ENG},
  {TITLE_TZNP3_PICKUP1_UKR, TITLE_TZNP3_PICKUP1_RUS, TITLE_TZNP3_PICKUP1_ENG},
  {TITLE_TZNP3_PICKUP2_UKR, TITLE_TZNP3_PICKUP2_RUS, TITLE_TZNP3_PICKUP2_ENG},

  {TITLE_TZNP4_PICKUP0_UKR, TITLE_TZNP4_PICKUP0_RUS, TITLE_TZNP4_PICKUP0_ENG},
  {TITLE_TZNP4_PICKUP1_UKR, TITLE_TZNP4_PICKUP1_RUS, TITLE_TZNP4_PICKUP1_ENG},
  {TITLE_TZNP4_PICKUP2_UKR, TITLE_TZNP4_PICKUP2_RUS, TITLE_TZNP4_PICKUP2_ENG},

  {TITLE_TZNP5_PICKUP0_UKR, TITLE_TZNP5_PICKUP0_RUS, TITLE_TZNP5_PICKUP0_ENG},
  {TITLE_TZNP5_PICKUP1_UKR, TITLE_TZNP5_PICKUP1_RUS, TITLE_TZNP5_PICKUP1_ENG},
  {TITLE_TZNP5_PICKUP2_UKR, TITLE_TZNP5_PICKUP2_RUS, TITLE_TZNP5_PICKUP2_ENG}
};
const TITLE TZNP_Delay_title[MAX_NUMBER_DELAY_TZNP] = 
{
  {TITLE_TZNP1_DELAY0_UKR, TITLE_TZNP1_DELAY0_RUS, TITLE_TZNP1_DELAY0_ENG},
  {TITLE_TZNP1_DELAY1_UKR, TITLE_TZNP1_DELAY1_RUS, TITLE_TZNP1_DELAY1_ENG},
  {TITLE_TZNP1_DELAY2_UKR, TITLE_TZNP1_DELAY2_RUS, TITLE_TZNP1_DELAY2_ENG},
  {TITLE_TZNP1_DELAY3_UKR, TITLE_TZNP1_DELAY3_RUS, TITLE_TZNP1_DELAY3_ENG},
  {TITLE_TZNP1_DELAY4_UKR, TITLE_TZNP1_DELAY4_RUS, TITLE_TZNP1_DELAY4_ENG},
  {TITLE_TZNP1_DELAY5_UKR, TITLE_TZNP1_DELAY5_RUS, TITLE_TZNP1_DELAY5_ENG},
  {TITLE_TZNP1_DELAY6_UKR, TITLE_TZNP1_DELAY6_RUS, TITLE_TZNP1_DELAY6_ENG},
  {TITLE_TZNP1_DELAY7_UKR, TITLE_TZNP1_DELAY7_RUS, TITLE_TZNP1_DELAY7_ENG},
  {TITLE_TZNP1_DELAY8_UKR, TITLE_TZNP1_DELAY8_RUS, TITLE_TZNP1_DELAY8_ENG},
  {TITLE_TZNP1_DELAY9_UKR, TITLE_TZNP1_DELAY9_RUS, TITLE_TZNP1_DELAY9_ENG},
  
  {TITLE_TZNP2_DELAY0_UKR, TITLE_TZNP2_DELAY0_RUS, TITLE_TZNP2_DELAY0_ENG},
  {TITLE_TZNP2_DELAY1_UKR, TITLE_TZNP2_DELAY1_RUS, TITLE_TZNP2_DELAY1_ENG},
  {TITLE_TZNP2_DELAY2_UKR, TITLE_TZNP2_DELAY2_RUS, TITLE_TZNP2_DELAY2_ENG},
  {TITLE_TZNP2_DELAY3_UKR, TITLE_TZNP2_DELAY3_RUS, TITLE_TZNP2_DELAY3_ENG},
  {TITLE_TZNP2_DELAY4_UKR, TITLE_TZNP2_DELAY4_RUS, TITLE_TZNP2_DELAY4_ENG},
  {TITLE_TZNP2_DELAY5_UKR, TITLE_TZNP2_DELAY5_RUS, TITLE_TZNP2_DELAY5_ENG},
  {TITLE_TZNP2_DELAY6_UKR, TITLE_TZNP2_DELAY6_RUS, TITLE_TZNP2_DELAY6_ENG},
  {TITLE_TZNP2_DELAY7_UKR, TITLE_TZNP2_DELAY7_RUS, TITLE_TZNP2_DELAY7_ENG},
  {TITLE_TZNP2_DELAY8_UKR, TITLE_TZNP2_DELAY8_RUS, TITLE_TZNP2_DELAY8_ENG},
  {TITLE_TZNP2_DELAY9_UKR, TITLE_TZNP2_DELAY9_RUS, TITLE_TZNP2_DELAY9_ENG},
  
  {TITLE_TZNP3_DELAY0_UKR, TITLE_TZNP3_DELAY0_RUS, TITLE_TZNP3_DELAY0_ENG},
  {TITLE_TZNP3_DELAY1_UKR, TITLE_TZNP3_DELAY1_RUS, TITLE_TZNP3_DELAY1_ENG},
  {TITLE_TZNP3_DELAY2_UKR, TITLE_TZNP3_DELAY2_RUS, TITLE_TZNP3_DELAY2_ENG},
  {TITLE_TZNP3_DELAY3_UKR, TITLE_TZNP3_DELAY3_RUS, TITLE_TZNP3_DELAY3_ENG},
  {TITLE_TZNP3_DELAY4_UKR, TITLE_TZNP3_DELAY4_RUS, TITLE_TZNP3_DELAY4_ENG},
  {TITLE_TZNP3_DELAY5_UKR, TITLE_TZNP3_DELAY5_RUS, TITLE_TZNP3_DELAY5_ENG},
  {TITLE_TZNP3_DELAY6_UKR, TITLE_TZNP3_DELAY6_RUS, TITLE_TZNP3_DELAY6_ENG},
  {TITLE_TZNP3_DELAY7_UKR, TITLE_TZNP3_DELAY7_RUS, TITLE_TZNP3_DELAY7_ENG},
  {TITLE_TZNP3_DELAY8_UKR, TITLE_TZNP3_DELAY8_RUS, TITLE_TZNP3_DELAY8_ENG},
  {TITLE_TZNP3_DELAY9_UKR, TITLE_TZNP3_DELAY9_RUS, TITLE_TZNP3_DELAY9_ENG},
  
  {TITLE_TZNP4_DELAY0_UKR, TITLE_TZNP4_DELAY0_RUS, TITLE_TZNP4_DELAY0_ENG},
  {TITLE_TZNP4_DELAY1_UKR, TITLE_TZNP4_DELAY1_RUS, TITLE_TZNP4_DELAY1_ENG},
  {TITLE_TZNP4_DELAY2_UKR, TITLE_TZNP4_DELAY2_RUS, TITLE_TZNP4_DELAY2_ENG},
  {TITLE_TZNP4_DELAY3_UKR, TITLE_TZNP4_DELAY3_RUS, TITLE_TZNP4_DELAY3_ENG},
  {TITLE_TZNP4_DELAY4_UKR, TITLE_TZNP4_DELAY4_RUS, TITLE_TZNP4_DELAY4_ENG},
  {TITLE_TZNP4_DELAY5_UKR, TITLE_TZNP4_DELAY5_RUS, TITLE_TZNP4_DELAY5_ENG},
  {TITLE_TZNP4_DELAY6_UKR, TITLE_TZNP4_DELAY6_RUS, TITLE_TZNP4_DELAY6_ENG},
  {TITLE_TZNP4_DELAY7_UKR, TITLE_TZNP4_DELAY7_RUS, TITLE_TZNP4_DELAY7_ENG},
  {TITLE_TZNP4_DELAY8_UKR, TITLE_TZNP4_DELAY8_RUS, TITLE_TZNP4_DELAY8_ENG},
  {TITLE_TZNP4_DELAY9_UKR, TITLE_TZNP4_DELAY9_RUS, TITLE_TZNP4_DELAY9_ENG},
  
  {TITLE_TZNP5_DELAY0_UKR, TITLE_TZNP5_DELAY0_RUS, TITLE_TZNP5_DELAY0_ENG},
  {TITLE_TZNP5_DELAY1_UKR, TITLE_TZNP5_DELAY1_RUS, TITLE_TZNP5_DELAY1_ENG},
  {TITLE_TZNP5_DELAY2_UKR, TITLE_TZNP5_DELAY2_RUS, TITLE_TZNP5_DELAY2_ENG},
  {TITLE_TZNP5_DELAY3_UKR, TITLE_TZNP5_DELAY3_RUS, TITLE_TZNP5_DELAY3_ENG},
  {TITLE_TZNP5_DELAY4_UKR, TITLE_TZNP5_DELAY4_RUS, TITLE_TZNP5_DELAY4_ENG},
  {TITLE_TZNP5_DELAY5_UKR, TITLE_TZNP5_DELAY5_RUS, TITLE_TZNP5_DELAY5_ENG},
  {TITLE_TZNP5_DELAY6_UKR, TITLE_TZNP5_DELAY6_RUS, TITLE_TZNP5_DELAY6_ENG},
  {TITLE_TZNP5_DELAY7_UKR, TITLE_TZNP5_DELAY7_RUS, TITLE_TZNP5_DELAY7_ENG},
  {TITLE_TZNP5_DELAY8_UKR, TITLE_TZNP5_DELAY8_RUS, TITLE_TZNP5_DELAY8_ENG},
  {TITLE_TZNP5_DELAY9_UKR, TITLE_TZNP5_DELAY9_RUS, TITLE_TZNP5_DELAY9_ENG},
};

const TITLE TZNP_State_title[MAX_NUMBER_CTRL_TZNP] = 
{
  {TITLE_TZNP1_STATE0_UKR, TITLE_TZNP1_STATE0_RUS, TITLE_TZNP1_STATE0_ENG},
  {TITLE_TZNP1_STATE1_UKR, TITLE_TZNP1_STATE1_RUS, TITLE_TZNP1_STATE1_ENG},
  {TITLE_TZNP1_STATE2_UKR, TITLE_TZNP1_STATE2_RUS, TITLE_TZNP1_STATE2_ENG},
  {TITLE_TZNP1_STATE3_UKR, TITLE_TZNP1_STATE3_RUS, TITLE_TZNP1_STATE3_ENG},
  {TITLE_TZNP1_STATE4_UKR, TITLE_TZNP1_STATE4_RUS, TITLE_TZNP1_STATE4_ENG},
  {TITLE_TZNP1_STATE5_UKR, TITLE_TZNP1_STATE5_RUS, TITLE_TZNP1_STATE5_ENG},
  {TITLE_TZNP1_STATE6_UKR, TITLE_TZNP1_STATE6_RUS, TITLE_TZNP1_STATE6_ENG},
  
  {TITLE_TZNP2_STATE0_UKR, TITLE_TZNP2_STATE0_RUS, TITLE_TZNP2_STATE0_ENG},
  {TITLE_TZNP2_STATE1_UKR, TITLE_TZNP2_STATE1_RUS, TITLE_TZNP2_STATE1_ENG},
  {TITLE_TZNP2_STATE2_UKR, TITLE_TZNP2_STATE2_RUS, TITLE_TZNP2_STATE2_ENG},
  {TITLE_TZNP2_STATE3_UKR, TITLE_TZNP2_STATE3_RUS, TITLE_TZNP2_STATE3_ENG},
  {TITLE_TZNP2_STATE4_UKR, TITLE_TZNP2_STATE4_RUS, TITLE_TZNP2_STATE4_ENG},
  {TITLE_TZNP2_STATE5_UKR, TITLE_TZNP2_STATE5_RUS, TITLE_TZNP2_STATE5_ENG},
  {TITLE_TZNP2_STATE6_UKR, TITLE_TZNP2_STATE6_RUS, TITLE_TZNP2_STATE6_ENG},

  {TITLE_TZNP3_STATE0_UKR, TITLE_TZNP3_STATE0_RUS, TITLE_TZNP3_STATE0_ENG},
  {TITLE_TZNP3_STATE1_UKR, TITLE_TZNP3_STATE1_RUS, TITLE_TZNP3_STATE1_ENG},
  {TITLE_TZNP3_STATE2_UKR, TITLE_TZNP3_STATE2_RUS, TITLE_TZNP3_STATE2_ENG},
  {TITLE_TZNP3_STATE3_UKR, TITLE_TZNP3_STATE3_RUS, TITLE_TZNP3_STATE3_ENG},
  {TITLE_TZNP3_STATE4_UKR, TITLE_TZNP3_STATE4_RUS, TITLE_TZNP3_STATE4_ENG},
  {TITLE_TZNP3_STATE5_UKR, TITLE_TZNP3_STATE5_RUS, TITLE_TZNP3_STATE5_ENG},
  {TITLE_TZNP3_STATE6_UKR, TITLE_TZNP3_STATE6_RUS, TITLE_TZNP3_STATE6_ENG},
  
  {TITLE_TZNP4_STATE0_UKR, TITLE_TZNP4_STATE0_RUS, TITLE_TZNP4_STATE0_ENG},
  {TITLE_TZNP4_STATE1_UKR, TITLE_TZNP4_STATE1_RUS, TITLE_TZNP4_STATE1_ENG},
  {TITLE_TZNP4_STATE2_UKR, TITLE_TZNP4_STATE2_RUS, TITLE_TZNP4_STATE2_ENG},
  {TITLE_TZNP4_STATE3_UKR, TITLE_TZNP4_STATE3_RUS, TITLE_TZNP4_STATE3_ENG},
  {TITLE_TZNP4_STATE4_UKR, TITLE_TZNP4_STATE4_RUS, TITLE_TZNP4_STATE4_ENG},
  {TITLE_TZNP4_STATE5_UKR, TITLE_TZNP4_STATE5_RUS, TITLE_TZNP4_STATE5_ENG},
  {TITLE_TZNP4_STATE6_UKR, TITLE_TZNP4_STATE6_RUS, TITLE_TZNP4_STATE6_ENG},
  
  {TITLE_TZNP5_STATE0_UKR, TITLE_TZNP5_STATE0_RUS, TITLE_TZNP5_STATE0_ENG},
  {TITLE_TZNP5_STATE1_UKR, TITLE_TZNP5_STATE1_RUS, TITLE_TZNP5_STATE1_ENG},
  {TITLE_TZNP5_STATE2_UKR, TITLE_TZNP5_STATE2_RUS, TITLE_TZNP5_STATE2_ENG},
  {TITLE_TZNP5_STATE3_UKR, TITLE_TZNP5_STATE3_RUS, TITLE_TZNP5_STATE3_ENG},
  {TITLE_TZNP5_STATE4_UKR, TITLE_TZNP5_STATE4_RUS, TITLE_TZNP5_STATE4_ENG},
  {TITLE_TZNP5_STATE5_UKR, TITLE_TZNP5_STATE5_RUS, TITLE_TZNP5_STATE5_ENG},
  {TITLE_TZNP5_STATE6_UKR, TITLE_TZNP5_STATE6_RUS, TITLE_TZNP5_STATE6_ENG}
};
int TZNP_select_group = 0;

WM_HWIN ZOP_FrameWin = WM_UNATTACHED, ZOP_MultiPage_groups, ZOP_Window_group, ZOP_MultiPage_type_info, ZOP_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_ZOP_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_ZOP = 0, _y_cbDelay_ZOP = 0, _y_cbControl_ZOP = 0;
WM_HWIN ZOP_Pickup_t[MAX_NUMBER_PICKUP_ZOP], ZOP_Pickup_v[MAX_NUMBER_PICKUP_ZOP], ZOP_Pickup_m[MAX_NUMBER_PICKUP_ZOP];
WM_HWIN ZOP_Delay_t[MAX_NUMBER_DELAY_ZOP], ZOP_Delay_v[MAX_NUMBER_DELAY_ZOP], ZOP_Delay_m[MAX_NUMBER_DELAY_ZOP];
WM_HWIN ZOP_State_t[MAX_NUMBER_CTRL_ZOP], ZOP_State_v[MAX_NUMBER_CTRL_ZOP];
const unsigned short int nalashtuvannja_ZOP[MAX_KILKIST_STUPENIV_ZOP + 1] = {MAX_NUMBER_CTRL_ZOP1, MAX_NUMBER_CTRL_ZOP2, MAX_NUMBER_CTRL_ZOP_G};

const TITLE ZOP_panel_title = {TITLE_ZOP_PANEL_UKR, TITLE_ZOP_PANEL_RUS, TITLE_ZOP_PANEL_ENG};

const TITLE ZOP_Pickup_title[MAX_NUMBER_PICKUP_ZOP] = 
{
  {TITLE_ZOP1_PICKUP0_UKR, TITLE_ZOP1_PICKUP0_RUS, TITLE_ZOP1_PICKUP0_ENG},
  {TITLE_ZOP1_PICKUP1_UKR, TITLE_ZOP1_PICKUP1_RUS, TITLE_ZOP1_PICKUP1_ENG},
  {TITLE_ZOP1_PICKUP2_UKR, TITLE_ZOP1_PICKUP2_RUS, TITLE_ZOP1_PICKUP2_ENG},
  {TITLE_ZOP1_PICKUP3_UKR, TITLE_ZOP1_PICKUP3_RUS, TITLE_ZOP1_PICKUP3_ENG},
  {TITLE_ZOP1_PICKUP4_UKR, TITLE_ZOP1_PICKUP4_RUS, TITLE_ZOP1_PICKUP4_ENG},
  {TITLE_ZOP1_PICKUP5_UKR, TITLE_ZOP1_PICKUP5_RUS, TITLE_ZOP1_PICKUP5_ENG},

  {TITLE_ZOP2_PICKUP0_UKR, TITLE_ZOP2_PICKUP0_RUS, TITLE_ZOP2_PICKUP0_ENG},
  {TITLE_ZOP2_PICKUP1_UKR, TITLE_ZOP2_PICKUP1_RUS, TITLE_ZOP2_PICKUP1_ENG},
  {TITLE_ZOP2_PICKUP2_UKR, TITLE_ZOP2_PICKUP2_RUS, TITLE_ZOP2_PICKUP2_ENG},
  {TITLE_ZOP2_PICKUP3_UKR, TITLE_ZOP2_PICKUP3_RUS, TITLE_ZOP2_PICKUP3_ENG},
  {TITLE_ZOP2_PICKUP4_UKR, TITLE_ZOP2_PICKUP4_RUS, TITLE_ZOP2_PICKUP4_ENG},
  {TITLE_ZOP1_PICKUP5_UKR, TITLE_ZOP2_PICKUP5_RUS, TITLE_ZOP2_PICKUP5_ENG}
};
const TITLE ZOP_Delay_title[MAX_NUMBER_DELAY_ZOP] = 
{
  {TITLE_ZOP1_DELAY0_UKR, TITLE_ZOP1_DELAY0_RUS, TITLE_ZOP1_DELAY0_ENG},
  {TITLE_ZOP1_DELAY1_UKR, TITLE_ZOP1_DELAY1_RUS, TITLE_ZOP1_DELAY1_ENG},
  {TITLE_ZOP1_DELAY2_UKR, TITLE_ZOP1_DELAY2_RUS, TITLE_ZOP1_DELAY2_ENG},

  {TITLE_ZOP2_DELAY0_UKR, TITLE_ZOP2_DELAY0_RUS, TITLE_ZOP2_DELAY0_ENG},
  {TITLE_ZOP2_DELAY1_UKR, TITLE_ZOP2_DELAY1_RUS, TITLE_ZOP2_DELAY1_ENG},
  {TITLE_ZOP2_DELAY2_UKR, TITLE_ZOP2_DELAY2_RUS, TITLE_ZOP2_DELAY2_ENG}
};

const TITLE ZOP_State_title[MAX_NUMBER_CTRL_ZOP] = 
{
  {TITLE_ZOP1_STATE0_UKR, TITLE_ZOP1_STATE0_RUS, TITLE_ZOP1_STATE0_ENG},
  {TITLE_ZOP1_STATE1_UKR, TITLE_ZOP1_STATE1_RUS, TITLE_ZOP1_STATE1_ENG},
  {TITLE_ZOP1_STATE2_UKR, TITLE_ZOP1_STATE2_RUS, TITLE_ZOP1_STATE2_ENG},
  
  {TITLE_ZOP2_STATE0_UKR, TITLE_ZOP2_STATE0_RUS, TITLE_ZOP2_STATE0_ENG},
  {TITLE_ZOP2_STATE1_UKR, TITLE_ZOP2_STATE1_RUS, TITLE_ZOP2_STATE1_ENG},
  {TITLE_ZOP2_STATE2_UKR, TITLE_ZOP2_STATE2_RUS, TITLE_ZOP2_STATE2_ENG}
};
int ZOP_select_group = 0;

WM_HWIN APV_FrameWin = WM_UNATTACHED, APV_MultiPage_groups, APV_Window_group, APV_MultiPage_type_info, APV_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_APV_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_APV = 0, _y_cbDelay_APV = 0, _y_cbControl_APV = 0;
WM_HWIN APV_Pickup_t[MAX_NUMBER_PICKUP_APV], APV_Pickup_v[MAX_NUMBER_PICKUP_APV], APV_Pickup_m[MAX_NUMBER_PICKUP_APV];
WM_HWIN APV_Delay_t[MAX_NUMBER_DELAY_APV], APV_Delay_v[MAX_NUMBER_DELAY_APV], APV_Delay_m[MAX_NUMBER_DELAY_APV];
WM_HWIN APV_State_t[MAX_NUMBER_CTRL_APV], APV_State_v[MAX_NUMBER_CTRL_APV];
const unsigned short int nalashtuvannja_APV[/*MAX_KILKIST_STUPENIV_APV + 1*/8] = {4, 5, 5, MAX_KILKIST_STUPENIV_MTZ, 3*MAX_KILKIST_STUPENIV_TZNP, MAX_KILKIST_STUPENIV_UMAX, MAX_KILKIST_STUPENIV_UMIN, MAX_KILKIST_STUPENIV_ZOP};

const TITLE APV_panel_title = {TITLE_APV_PANEL_UKR, TITLE_APV_PANEL_RUS, TITLE_APV_PANEL_ENG};

const TITLE APV_Pickup_title[MAX_NUMBER_PICKUP_APV] = 
{
  {TITLE_APV_PICKUP0_UKR, TITLE_APV_PICKUP0_RUS, TITLE_APV_PICKUP0_ENG},
  {TITLE_APV_PICKUP1_UKR, TITLE_APV_PICKUP1_RUS, TITLE_APV_PICKUP1_ENG},
  {TITLE_APV_PICKUP2_UKR, TITLE_APV_PICKUP2_RUS, TITLE_APV_PICKUP2_ENG},
  {TITLE_APV_PICKUP3_UKR, TITLE_APV_PICKUP3_RUS, TITLE_APV_PICKUP3_ENG},
  {TITLE_APV_PICKUP4_UKR, TITLE_APV_PICKUP4_RUS, TITLE_APV_PICKUP4_ENG},
  {TITLE_APV_PICKUP5_UKR, TITLE_APV_PICKUP5_RUS, TITLE_APV_PICKUP5_ENG},
  {TITLE_APV_PICKUP6_UKR, TITLE_APV_PICKUP6_RUS, TITLE_APV_PICKUP6_ENG},
};
const TITLE APV_Delay_title[MAX_NUMBER_DELAY_APV] = 
{
  {TITLE_APV_DELAY0_UKR, TITLE_APV_DELAY0_RUS, TITLE_APV_DELAY0_ENG},
  {TITLE_APV_DELAY1_UKR, TITLE_APV_DELAY1_RUS, TITLE_APV_DELAY1_ENG},
  {TITLE_APV_DELAY2_UKR, TITLE_APV_DELAY2_RUS, TITLE_APV_DELAY2_ENG},
  {TITLE_APV_DELAY3_UKR, TITLE_APV_DELAY3_RUS, TITLE_APV_DELAY3_ENG},
  {TITLE_APV_DELAY4_UKR, TITLE_APV_DELAY4_RUS, TITLE_APV_DELAY4_ENG},
  {TITLE_APV_DELAY5_UKR, TITLE_APV_DELAY5_RUS, TITLE_APV_DELAY5_ENG},
  {TITLE_APV_DELAY6_UKR, TITLE_APV_DELAY6_RUS, TITLE_APV_DELAY6_ENG},
  {TITLE_APV_DELAY7_UKR, TITLE_APV_DELAY7_RUS, TITLE_APV_DELAY7_ENG},
  {TITLE_APV_DELAY8_UKR, TITLE_APV_DELAY8_RUS, TITLE_APV_DELAY8_ENG},
  {TITLE_APV_DELAY9_UKR, TITLE_APV_DELAY9_RUS, TITLE_APV_DELAY9_ENG}
};

const TITLE REGYM_APV[5] = 
{
  {TITLE_REGYM_APV_0_UKR, TITLE_REGYM_APV_0_RUS, TITLE_REGYM_APV_0_ENG},
  {TITLE_REGYM_APV_1_UKR, TITLE_REGYM_APV_1_RUS, TITLE_REGYM_APV_1_ENG},
  {TITLE_REGYM_APV_2_UKR, TITLE_REGYM_APV_2_RUS, TITLE_REGYM_APV_2_ENG},
  {TITLE_REGYM_APV_3_UKR, TITLE_REGYM_APV_3_RUS, TITLE_REGYM_APV_3_ENG},
  {TITLE_REGYM_APV_4_UKR, TITLE_REGYM_APV_4_RUS, TITLE_REGYM_APV_4_ENG}
};
const TITLE APV_State_title[MAX_NUMBER_CTRL_APV] = 
{
  {TITLE_APV_STATE0_UKR, TITLE_APV_STATE0_RUS, TITLE_APV_STATE0_ENG},
  {TITLE_APV_STATE1_UKR, TITLE_APV_STATE1_RUS, TITLE_APV_STATE1_ENG},
  {TITLE_APV_STATE2_UKR, TITLE_APV_STATE2_RUS, TITLE_APV_STATE2_ENG},
  {TITLE_APV_STATE3_UKR, TITLE_APV_STATE3_RUS, TITLE_APV_STATE3_ENG},

  {TITLE_APV_STATE4_UKR, TITLE_APV_STATE4_RUS, TITLE_APV_STATE4_ENG},
  {TITLE_APV_STATE5_UKR, TITLE_APV_STATE5_RUS, TITLE_APV_STATE5_ENG},
  {TITLE_APV_STATE6_UKR, TITLE_APV_STATE6_RUS, TITLE_APV_STATE6_ENG},
  {TITLE_APV_STATE7_UKR, TITLE_APV_STATE7_RUS, TITLE_APV_STATE7_ENG},
  {TITLE_APV_STATE8_UKR, TITLE_APV_STATE8_RUS, TITLE_APV_STATE8_ENG},

  {TITLE_APV_STATE9_UKR, TITLE_APV_STATE9_RUS, TITLE_APV_STATE9_ENG},
  {TITLE_APV_STATE10_UKR, TITLE_APV_STATE10_RUS, TITLE_APV_STATE10_ENG},
  {TITLE_APV_STATE11_UKR, TITLE_APV_STATE11_RUS, TITLE_APV_STATE11_ENG},
  {TITLE_APV_STATE12_UKR, TITLE_APV_STATE12_RUS, TITLE_APV_STATE12_ENG},
  {TITLE_APV_STATE13_UKR, TITLE_APV_STATE13_RUS, TITLE_APV_STATE13_ENG},

  {TITLE_APV_STATE14_UKR, TITLE_APV_STATE14_RUS, TITLE_APV_STATE14_ENG},
  {TITLE_APV_STATE15_UKR, TITLE_APV_STATE15_RUS, TITLE_APV_STATE15_ENG},
  {TITLE_APV_STATE16_UKR, TITLE_APV_STATE16_RUS, TITLE_APV_STATE16_ENG},
  {TITLE_APV_STATE17_UKR, TITLE_APV_STATE17_RUS, TITLE_APV_STATE17_ENG},
  {TITLE_APV_STATE18_UKR, TITLE_APV_STATE18_RUS, TITLE_APV_STATE18_ENG},

  {TITLE_APV_STATE19_UKR, TITLE_APV_STATE19_RUS, TITLE_APV_STATE19_ENG},
  {TITLE_APV_STATE20_UKR, TITLE_APV_STATE20_RUS, TITLE_APV_STATE20_ENG},
  {TITLE_APV_STATE21_UKR, TITLE_APV_STATE21_RUS, TITLE_APV_STATE21_ENG},
  {TITLE_APV_STATE22_UKR, TITLE_APV_STATE22_RUS, TITLE_APV_STATE22_ENG},
  {TITLE_APV_STATE23_UKR, TITLE_APV_STATE23_RUS, TITLE_APV_STATE23_ENG},
  {TITLE_APV_STATE24_UKR, TITLE_APV_STATE24_RUS, TITLE_APV_STATE24_ENG},
  {TITLE_APV_STATE25_UKR, TITLE_APV_STATE25_RUS, TITLE_APV_STATE25_ENG},
  {TITLE_APV_STATE26_UKR, TITLE_APV_STATE26_RUS, TITLE_APV_STATE26_ENG},
  {TITLE_APV_STATE27_UKR, TITLE_APV_STATE27_RUS, TITLE_APV_STATE27_ENG},
  {TITLE_APV_STATE28_UKR, TITLE_APV_STATE28_RUS, TITLE_APV_STATE28_ENG},
  {TITLE_APV_STATE29_UKR, TITLE_APV_STATE29_RUS, TITLE_APV_STATE29_ENG},
  {TITLE_APV_STATE30_UKR, TITLE_APV_STATE30_RUS, TITLE_APV_STATE30_ENG},
  {TITLE_APV_STATE31_UKR, TITLE_APV_STATE31_RUS, TITLE_APV_STATE31_ENG},
  {TITLE_APV_STATE32_UKR, TITLE_APV_STATE32_RUS, TITLE_APV_STATE32_ENG},
  {TITLE_APV_STATE33_UKR, TITLE_APV_STATE33_RUS, TITLE_APV_STATE33_ENG},

  {TITLE_APV_STATE34_UKR, TITLE_APV_STATE34_RUS, TITLE_APV_STATE34_ENG},
  {TITLE_APV_STATE35_UKR, TITLE_APV_STATE35_RUS, TITLE_APV_STATE35_ENG},

  {TITLE_APV_STATE36_UKR, TITLE_APV_STATE36_RUS, TITLE_APV_STATE36_ENG},
  {TITLE_APV_STATE37_UKR, TITLE_APV_STATE37_RUS, TITLE_APV_STATE37_ENG},

  {TITLE_APV_STATE38_UKR, TITLE_APV_STATE38_RUS, TITLE_APV_STATE38_ENG},
  {TITLE_APV_STATE39_UKR, TITLE_APV_STATE39_RUS, TITLE_APV_STATE39_ENG}
};
int APV_select_group = 0;
unsigned char temp_data_for_APV;

WM_HWIN UROV_FrameWin = WM_UNATTACHED, UROV_MultiPage_groups, UROV_Window_group, UROV_MultiPage_type_info, UROV_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_UROV_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_UROV = 0, _y_cbDelay_UROV = 0, _y_cbControl_UROV = 0;
WM_HWIN UROV_Pickup_t[MAX_NUMBER_PICKUP_UROV], UROV_Pickup_v[MAX_NUMBER_PICKUP_UROV], UROV_Pickup_m[MAX_NUMBER_PICKUP_UROV];
WM_HWIN UROV_Delay_t[MAX_NUMBER_DELAY_UROV], UROV_Delay_v[MAX_NUMBER_DELAY_UROV], UROV_Delay_m[MAX_NUMBER_DELAY_UROV];
WM_HWIN UROV_State_t[MAX_NUMBER_CTRL_UROV], UROV_State_v[MAX_NUMBER_CTRL_UROV];
const unsigned short int nalashtuvannja_UROV[/*MAX_KILKIST_STUPENIV_UROV + 1*/8] = {1, 5, 5, MAX_KILKIST_STUPENIV_MTZ, 3*MAX_KILKIST_STUPENIV_TZNP, MAX_KILKIST_STUPENIV_UMAX, MAX_KILKIST_STUPENIV_UMIN, MAX_KILKIST_STUPENIV_ZOP};

const TITLE UROV_panel_title = {TITLE_UROV_PANEL_UKR, TITLE_UROV_PANEL_RUS, TITLE_UROV_PANEL_ENG};

const TITLE UROV_Pickup_title[MAX_NUMBER_PICKUP_UROV] = 
{
  {TITLE_UROV_PICKUP0_UKR, TITLE_UROV_PICKUP0_RUS, TITLE_UROV_PICKUP0_ENG}
};
const TITLE UROV_Delay_title[MAX_NUMBER_DELAY_UROV] = 
{
  {TITLE_UROV_DELAY0_UKR, TITLE_UROV_DELAY0_RUS, TITLE_UROV_DELAY0_ENG},
  {TITLE_UROV_DELAY1_UKR, TITLE_UROV_DELAY1_RUS, TITLE_UROV_DELAY1_ENG}
};

const TITLE UROV_State_title[MAX_NUMBER_CTRL_UROV] = 
{
  {TITLE_UROV_STATE0_UKR, TITLE_UROV_STATE0_RUS, TITLE_UROV_STATE0_ENG},

  {TITLE_UROV_STATE1_UKR, TITLE_UROV_STATE1_RUS, TITLE_UROV_STATE1_ENG},
  {TITLE_UROV_STATE2_UKR, TITLE_UROV_STATE2_RUS, TITLE_UROV_STATE2_ENG},
  {TITLE_UROV_STATE3_UKR, TITLE_UROV_STATE3_RUS, TITLE_UROV_STATE3_ENG},
  {TITLE_UROV_STATE4_UKR, TITLE_UROV_STATE4_RUS, TITLE_UROV_STATE4_ENG},
  {TITLE_UROV_STATE5_UKR, TITLE_UROV_STATE5_RUS, TITLE_UROV_STATE5_ENG},

  {TITLE_UROV_STATE6_UKR, TITLE_UROV_STATE6_RUS, TITLE_UROV_STATE6_ENG},
  {TITLE_UROV_STATE7_UKR, TITLE_UROV_STATE7_RUS, TITLE_UROV_STATE7_ENG},
  {TITLE_UROV_STATE8_UKR, TITLE_UROV_STATE8_RUS, TITLE_UROV_STATE8_ENG},
  {TITLE_UROV_STATE9_UKR, TITLE_UROV_STATE9_RUS, TITLE_UROV_STATE9_ENG},
  {TITLE_UROV_STATE10_UKR, TITLE_UROV_STATE10_RUS, TITLE_UROV_STATE10_ENG},

  {TITLE_UROV_STATE11_UKR, TITLE_UROV_STATE11_RUS, TITLE_UROV_STATE11_ENG},
  {TITLE_UROV_STATE12_UKR, TITLE_UROV_STATE12_RUS, TITLE_UROV_STATE12_ENG},
  {TITLE_UROV_STATE13_UKR, TITLE_UROV_STATE13_RUS, TITLE_UROV_STATE13_ENG},
  {TITLE_UROV_STATE14_UKR, TITLE_UROV_STATE14_RUS, TITLE_UROV_STATE14_ENG},

  {TITLE_UROV_STATE15_UKR, TITLE_UROV_STATE15_RUS, TITLE_UROV_STATE15_ENG},
  {TITLE_UROV_STATE16_UKR, TITLE_UROV_STATE16_RUS, TITLE_UROV_STATE16_ENG},
  {TITLE_UROV_STATE17_UKR, TITLE_UROV_STATE17_RUS, TITLE_UROV_STATE17_ENG},
  {TITLE_UROV_STATE18_UKR, TITLE_UROV_STATE18_RUS, TITLE_UROV_STATE18_ENG},
  {TITLE_UROV_STATE19_UKR, TITLE_UROV_STATE19_RUS, TITLE_UROV_STATE19_ENG},
  {TITLE_UROV_STATE20_UKR, TITLE_UROV_STATE20_RUS, TITLE_UROV_STATE20_ENG},
  {TITLE_UROV_STATE21_UKR, TITLE_UROV_STATE21_RUS, TITLE_UROV_STATE21_ENG},
  {TITLE_UROV_STATE22_UKR, TITLE_UROV_STATE22_RUS, TITLE_UROV_STATE22_ENG},
  {TITLE_UROV_STATE23_UKR, TITLE_UROV_STATE23_RUS, TITLE_UROV_STATE23_ENG},
  {TITLE_UROV_STATE24_UKR, TITLE_UROV_STATE24_RUS, TITLE_UROV_STATE24_ENG},
  {TITLE_UROV_STATE25_UKR, TITLE_UROV_STATE25_RUS, TITLE_UROV_STATE25_ENG},
  {TITLE_UROV_STATE26_UKR, TITLE_UROV_STATE26_RUS, TITLE_UROV_STATE26_ENG},
  {TITLE_UROV_STATE27_UKR, TITLE_UROV_STATE27_RUS, TITLE_UROV_STATE27_ENG},
  {TITLE_UROV_STATE28_UKR, TITLE_UROV_STATE28_RUS, TITLE_UROV_STATE28_ENG},
  {TITLE_UROV_STATE29_UKR, TITLE_UROV_STATE29_RUS, TITLE_UROV_STATE29_ENG},
  {TITLE_UROV_STATE30_UKR, TITLE_UROV_STATE30_RUS, TITLE_UROV_STATE30_ENG},

  {TITLE_UROV_STATE31_UKR, TITLE_UROV_STATE31_RUS, TITLE_UROV_STATE31_ENG},
  {TITLE_UROV_STATE32_UKR, TITLE_UROV_STATE32_RUS, TITLE_UROV_STATE32_ENG},

  {TITLE_UROV_STATE33_UKR, TITLE_UROV_STATE33_RUS, TITLE_UROV_STATE33_ENG},
  {TITLE_UROV_STATE34_UKR, TITLE_UROV_STATE34_RUS, TITLE_UROV_STATE34_ENG},

  {TITLE_UROV_STATE35_UKR, TITLE_UROV_STATE35_RUS, TITLE_UROV_STATE35_ENG},
  {TITLE_UROV_STATE36_UKR, TITLE_UROV_STATE36_RUS, TITLE_UROV_STATE36_ENG}
};
int UROV_select_group = 0;
unsigned char temp_data_for_UROV;

WM_HWIN DZ_FrameWin = WM_UNATTACHED, DZ_MultiPage_groups, DZ_Window_group, DZ_MultiPage_type_info, DZ_Pages[MAX_PAGES_PROTECTION_SDC];
WM_HWIN DZ_SubPages_delay[2];
SCROLLBAR_Handle ScrollBar_DZ_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_DZ_SubPages_delay[2];
int _y_cbPickup_DZ = 0, _y_cbDelay_DZ = 0, _y_cbDelay_DZ_g = 0, _y_cbControl_DZ = 0;
WM_HWIN DZ_Pickup_t[MAX_NUMBER_PICKUP_DZ], DZ_Pickup_v[MAX_NUMBER_PICKUP_DZ], DZ_Pickup_m[MAX_NUMBER_PICKUP_DZ];
WM_HWIN DZ_Delay_t[MAX_NUMBER_DELAY_DZ + MAX_NUMBER_DELAY_DZ_G], DZ_Delay_v[MAX_NUMBER_DELAY_DZ + MAX_NUMBER_DELAY_DZ_G], DZ_Delay_m[MAX_NUMBER_DELAY_DZ + MAX_NUMBER_DELAY_DZ_G];
WM_HWIN DZ_State_t[MAX_NUMBER_CTRL_DZ], DZ_State_v[MAX_NUMBER_CTRL_DZ];
const unsigned short int nalashtuvannja_DZ[MAX_KILKIST_STUPENIV_DZ + 1] = {MAX_NUMBER_CTRL_DZ1, MAX_NUMBER_CTRL_DZ2, MAX_NUMBER_CTRL_DZ3, MAX_NUMBER_CTRL_DZ4, MAX_NUMBER_CTRL_DZ5, MAX_NUMBER_CTRL_DZ_G};

const TITLE DZ_panel_title = {TITLE_DZ_PANEL_UKR, TITLE_DZ_PANEL_RUS, TITLE_DZ_PANEL_ENG};

const TITLE DZ_Pickup_title[MAX_NUMBER_PICKUP_DZ] = 
{
  {TITLE_DZ1_PICKUP0_UKR , TITLE_DZ1_PICKUP0_RUS , TITLE_DZ1_PICKUP0_ENG },
  {TITLE_DZ1_PICKUP1_UKR , TITLE_DZ1_PICKUP1_RUS , TITLE_DZ1_PICKUP1_ENG },
  {TITLE_DZ1_PICKUP2_UKR , TITLE_DZ1_PICKUP2_RUS , TITLE_DZ1_PICKUP2_ENG },
  {TITLE_DZ1_PICKUP3_UKR , TITLE_DZ1_PICKUP3_RUS , TITLE_DZ1_PICKUP3_ENG },
  {TITLE_DZ1_PICKUP4_UKR , TITLE_DZ1_PICKUP4_RUS , TITLE_DZ1_PICKUP4_ENG },
  {TITLE_DZ1_PICKUP5_UKR , TITLE_DZ1_PICKUP5_RUS , TITLE_DZ1_PICKUP5_ENG },
  {TITLE_DZ1_PICKUP6_UKR , TITLE_DZ1_PICKUP6_RUS , TITLE_DZ1_PICKUP6_ENG },
  {TITLE_DZ1_PICKUP7_UKR , TITLE_DZ1_PICKUP7_RUS , TITLE_DZ1_PICKUP7_ENG },
  {TITLE_DZ1_PICKUP8_UKR , TITLE_DZ1_PICKUP8_RUS , TITLE_DZ1_PICKUP8_ENG },
  {TITLE_DZ1_PICKUP9_UKR , TITLE_DZ1_PICKUP9_RUS , TITLE_DZ1_PICKUP9_ENG },
  {TITLE_DZ1_PICKUP10_UKR, TITLE_DZ1_PICKUP10_RUS, TITLE_DZ1_PICKUP10_ENG},
  {TITLE_DZ1_PICKUP11_UKR, TITLE_DZ1_PICKUP11_RUS, TITLE_DZ1_PICKUP11_ENG},
  {TITLE_DZ1_PICKUP12_UKR, TITLE_DZ1_PICKUP12_RUS, TITLE_DZ1_PICKUP12_ENG},
  {TITLE_DZ1_PICKUP13_UKR, TITLE_DZ1_PICKUP13_RUS, TITLE_DZ1_PICKUP13_ENG},
  {TITLE_DZ1_PICKUP14_UKR, TITLE_DZ1_PICKUP14_RUS, TITLE_DZ1_PICKUP14_ENG},
  {TITLE_DZ1_PICKUP15_UKR, TITLE_DZ1_PICKUP15_RUS, TITLE_DZ1_PICKUP15_ENG},
  {TITLE_DZ1_PICKUP16_UKR, TITLE_DZ1_PICKUP16_RUS, TITLE_DZ1_PICKUP16_ENG},
  {TITLE_DZ1_PICKUP17_UKR, TITLE_DZ1_PICKUP17_RUS, TITLE_DZ1_PICKUP17_ENG},

  {TITLE_DZ2_PICKUP0_UKR , TITLE_DZ2_PICKUP0_RUS , TITLE_DZ2_PICKUP0_ENG },
  {TITLE_DZ2_PICKUP1_UKR , TITLE_DZ2_PICKUP1_RUS , TITLE_DZ2_PICKUP1_ENG },
  {TITLE_DZ2_PICKUP2_UKR , TITLE_DZ2_PICKUP2_RUS , TITLE_DZ2_PICKUP2_ENG },
  {TITLE_DZ2_PICKUP3_UKR , TITLE_DZ2_PICKUP3_RUS , TITLE_DZ2_PICKUP3_ENG },
  {TITLE_DZ2_PICKUP4_UKR , TITLE_DZ2_PICKUP4_RUS , TITLE_DZ2_PICKUP4_ENG },
  {TITLE_DZ2_PICKUP5_UKR , TITLE_DZ2_PICKUP5_RUS , TITLE_DZ2_PICKUP5_ENG },
  {TITLE_DZ2_PICKUP6_UKR , TITLE_DZ2_PICKUP6_RUS , TITLE_DZ2_PICKUP6_ENG },
  {TITLE_DZ2_PICKUP7_UKR , TITLE_DZ2_PICKUP7_RUS , TITLE_DZ2_PICKUP7_ENG },
  {TITLE_DZ2_PICKUP8_UKR , TITLE_DZ2_PICKUP8_RUS , TITLE_DZ2_PICKUP8_ENG },
  {TITLE_DZ2_PICKUP9_UKR , TITLE_DZ2_PICKUP9_RUS , TITLE_DZ2_PICKUP9_ENG },
  {TITLE_DZ2_PICKUP10_UKR, TITLE_DZ2_PICKUP10_RUS, TITLE_DZ2_PICKUP10_ENG},
  {TITLE_DZ2_PICKUP11_UKR, TITLE_DZ2_PICKUP11_RUS, TITLE_DZ2_PICKUP11_ENG},
  {TITLE_DZ2_PICKUP12_UKR, TITLE_DZ2_PICKUP12_RUS, TITLE_DZ2_PICKUP12_ENG},
  {TITLE_DZ2_PICKUP13_UKR, TITLE_DZ2_PICKUP13_RUS, TITLE_DZ2_PICKUP13_ENG},
  {TITLE_DZ2_PICKUP14_UKR, TITLE_DZ2_PICKUP14_RUS, TITLE_DZ2_PICKUP14_ENG},
  {TITLE_DZ2_PICKUP15_UKR, TITLE_DZ2_PICKUP15_RUS, TITLE_DZ2_PICKUP15_ENG},
  {TITLE_DZ2_PICKUP16_UKR, TITLE_DZ2_PICKUP16_RUS, TITLE_DZ2_PICKUP16_ENG},
  {TITLE_DZ2_PICKUP17_UKR, TITLE_DZ2_PICKUP17_RUS, TITLE_DZ2_PICKUP17_ENG},

  {TITLE_DZ3_PICKUP0_UKR , TITLE_DZ3_PICKUP0_RUS , TITLE_DZ3_PICKUP0_ENG },
  {TITLE_DZ3_PICKUP1_UKR , TITLE_DZ3_PICKUP1_RUS , TITLE_DZ3_PICKUP1_ENG },
  {TITLE_DZ3_PICKUP2_UKR , TITLE_DZ3_PICKUP2_RUS , TITLE_DZ3_PICKUP2_ENG },
  {TITLE_DZ3_PICKUP3_UKR , TITLE_DZ3_PICKUP3_RUS , TITLE_DZ3_PICKUP3_ENG },
  {TITLE_DZ3_PICKUP4_UKR , TITLE_DZ3_PICKUP4_RUS , TITLE_DZ3_PICKUP4_ENG },
  {TITLE_DZ3_PICKUP5_UKR , TITLE_DZ3_PICKUP5_RUS , TITLE_DZ3_PICKUP5_ENG },
  {TITLE_DZ3_PICKUP6_UKR , TITLE_DZ3_PICKUP6_RUS , TITLE_DZ3_PICKUP6_ENG },
  {TITLE_DZ3_PICKUP7_UKR , TITLE_DZ3_PICKUP7_RUS , TITLE_DZ3_PICKUP7_ENG },
  {TITLE_DZ3_PICKUP8_UKR , TITLE_DZ3_PICKUP8_RUS , TITLE_DZ3_PICKUP8_ENG },
  {TITLE_DZ3_PICKUP9_UKR , TITLE_DZ3_PICKUP9_RUS , TITLE_DZ3_PICKUP9_ENG },
  {TITLE_DZ3_PICKUP10_UKR, TITLE_DZ3_PICKUP10_RUS, TITLE_DZ3_PICKUP10_ENG},
  {TITLE_DZ3_PICKUP11_UKR, TITLE_DZ3_PICKUP11_RUS, TITLE_DZ3_PICKUP11_ENG},
  {TITLE_DZ3_PICKUP12_UKR, TITLE_DZ3_PICKUP12_RUS, TITLE_DZ3_PICKUP12_ENG},
  {TITLE_DZ3_PICKUP13_UKR, TITLE_DZ3_PICKUP13_RUS, TITLE_DZ3_PICKUP13_ENG},
  {TITLE_DZ3_PICKUP14_UKR, TITLE_DZ3_PICKUP14_RUS, TITLE_DZ3_PICKUP14_ENG},
  {TITLE_DZ3_PICKUP15_UKR, TITLE_DZ3_PICKUP15_RUS, TITLE_DZ3_PICKUP15_ENG},
  {TITLE_DZ3_PICKUP16_UKR, TITLE_DZ3_PICKUP16_RUS, TITLE_DZ3_PICKUP16_ENG},
  {TITLE_DZ3_PICKUP17_UKR, TITLE_DZ3_PICKUP17_RUS, TITLE_DZ3_PICKUP17_ENG},

  {TITLE_DZ4_PICKUP0_UKR , TITLE_DZ4_PICKUP0_RUS , TITLE_DZ4_PICKUP0_ENG },
  {TITLE_DZ4_PICKUP1_UKR , TITLE_DZ4_PICKUP1_RUS , TITLE_DZ4_PICKUP1_ENG },
  {TITLE_DZ4_PICKUP2_UKR , TITLE_DZ4_PICKUP2_RUS , TITLE_DZ4_PICKUP2_ENG },
  {TITLE_DZ4_PICKUP3_UKR , TITLE_DZ4_PICKUP3_RUS , TITLE_DZ4_PICKUP3_ENG },
  {TITLE_DZ4_PICKUP4_UKR , TITLE_DZ4_PICKUP4_RUS , TITLE_DZ4_PICKUP4_ENG },
  {TITLE_DZ4_PICKUP5_UKR , TITLE_DZ4_PICKUP5_RUS , TITLE_DZ4_PICKUP5_ENG },
  {TITLE_DZ4_PICKUP6_UKR , TITLE_DZ4_PICKUP6_RUS , TITLE_DZ4_PICKUP6_ENG },
  {TITLE_DZ4_PICKUP7_UKR , TITLE_DZ4_PICKUP7_RUS , TITLE_DZ4_PICKUP7_ENG },
  {TITLE_DZ4_PICKUP8_UKR , TITLE_DZ4_PICKUP8_RUS , TITLE_DZ4_PICKUP8_ENG },
  {TITLE_DZ4_PICKUP9_UKR , TITLE_DZ4_PICKUP9_RUS , TITLE_DZ4_PICKUP9_ENG },
  {TITLE_DZ4_PICKUP10_UKR, TITLE_DZ4_PICKUP10_RUS, TITLE_DZ4_PICKUP10_ENG},
  {TITLE_DZ4_PICKUP11_UKR, TITLE_DZ4_PICKUP11_RUS, TITLE_DZ4_PICKUP11_ENG},
  {TITLE_DZ4_PICKUP12_UKR, TITLE_DZ4_PICKUP12_RUS, TITLE_DZ4_PICKUP12_ENG},
  {TITLE_DZ4_PICKUP13_UKR, TITLE_DZ4_PICKUP13_RUS, TITLE_DZ4_PICKUP13_ENG},
  {TITLE_DZ4_PICKUP14_UKR, TITLE_DZ4_PICKUP14_RUS, TITLE_DZ4_PICKUP14_ENG},
  {TITLE_DZ4_PICKUP15_UKR, TITLE_DZ4_PICKUP15_RUS, TITLE_DZ4_PICKUP15_ENG},
  {TITLE_DZ4_PICKUP16_UKR, TITLE_DZ4_PICKUP16_RUS, TITLE_DZ4_PICKUP16_ENG},
  {TITLE_DZ4_PICKUP17_UKR, TITLE_DZ4_PICKUP17_RUS, TITLE_DZ4_PICKUP17_ENG},

  {TITLE_DZ5_PICKUP0_UKR , TITLE_DZ5_PICKUP0_RUS , TITLE_DZ5_PICKUP0_ENG },
  {TITLE_DZ5_PICKUP1_UKR , TITLE_DZ5_PICKUP1_RUS , TITLE_DZ5_PICKUP1_ENG },
  {TITLE_DZ5_PICKUP2_UKR , TITLE_DZ5_PICKUP2_RUS , TITLE_DZ5_PICKUP2_ENG },
  {TITLE_DZ5_PICKUP3_UKR , TITLE_DZ5_PICKUP3_RUS , TITLE_DZ5_PICKUP3_ENG },
  {TITLE_DZ5_PICKUP4_UKR , TITLE_DZ5_PICKUP4_RUS , TITLE_DZ5_PICKUP4_ENG },
  {TITLE_DZ5_PICKUP5_UKR , TITLE_DZ5_PICKUP5_RUS , TITLE_DZ5_PICKUP5_ENG },
  {TITLE_DZ5_PICKUP6_UKR , TITLE_DZ5_PICKUP6_RUS , TITLE_DZ5_PICKUP6_ENG },
  {TITLE_DZ5_PICKUP7_UKR , TITLE_DZ5_PICKUP7_RUS , TITLE_DZ5_PICKUP7_ENG },
  {TITLE_DZ5_PICKUP8_UKR , TITLE_DZ5_PICKUP8_RUS , TITLE_DZ5_PICKUP8_ENG },
  {TITLE_DZ5_PICKUP9_UKR , TITLE_DZ5_PICKUP9_RUS , TITLE_DZ5_PICKUP9_ENG },
  {TITLE_DZ5_PICKUP10_UKR, TITLE_DZ5_PICKUP10_RUS, TITLE_DZ5_PICKUP10_ENG},
  {TITLE_DZ5_PICKUP11_UKR, TITLE_DZ5_PICKUP11_RUS, TITLE_DZ5_PICKUP11_ENG},
  {TITLE_DZ5_PICKUP12_UKR, TITLE_DZ5_PICKUP12_RUS, TITLE_DZ5_PICKUP12_ENG},
  {TITLE_DZ5_PICKUP13_UKR, TITLE_DZ5_PICKUP13_RUS, TITLE_DZ5_PICKUP13_ENG},
  {TITLE_DZ5_PICKUP14_UKR, TITLE_DZ5_PICKUP14_RUS, TITLE_DZ5_PICKUP14_ENG},
  {TITLE_DZ5_PICKUP15_UKR, TITLE_DZ5_PICKUP15_RUS, TITLE_DZ5_PICKUP15_ENG},
  {TITLE_DZ5_PICKUP16_UKR, TITLE_DZ5_PICKUP16_RUS, TITLE_DZ5_PICKUP16_ENG},
  {TITLE_DZ5_PICKUP17_UKR, TITLE_DZ5_PICKUP17_RUS, TITLE_DZ5_PICKUP17_ENG},

  {TITLE_KOL_MF_DZ_PICKUP0_UKR, TITLE_KOL_MF_DZ_PICKUP0_RUS, TITLE_KOL_MF_DZ_PICKUP0_ENG},
  {TITLE_KOL_MF_DZ_PICKUP1_UKR, TITLE_KOL_MF_DZ_PICKUP1_RUS, TITLE_KOL_MF_DZ_PICKUP1_ENG},
  {TITLE_KOL_MF_DZ_PICKUP2_UKR, TITLE_KOL_MF_DZ_PICKUP2_RUS, TITLE_KOL_MF_DZ_PICKUP2_ENG},
  {TITLE_KOL_MF_DZ_PICKUP3_UKR, TITLE_KOL_MF_DZ_PICKUP3_RUS, TITLE_KOL_MF_DZ_PICKUP3_ENG},
  {TITLE_KOL_MF_DZ_PICKUP4_UKR, TITLE_KOL_MF_DZ_PICKUP4_RUS, TITLE_KOL_MF_DZ_PICKUP4_ENG},
  {TITLE_KOL_MF_DZ_PICKUP5_UKR, TITLE_KOL_MF_DZ_PICKUP5_RUS, TITLE_KOL_MF_DZ_PICKUP5_ENG},
  {TITLE_KOL_MF_DZ_PICKUP6_UKR, TITLE_KOL_MF_DZ_PICKUP6_RUS, TITLE_KOL_MF_DZ_PICKUP6_ENG},
  {TITLE_KOL_MF_DZ_PICKUP7_UKR, TITLE_KOL_MF_DZ_PICKUP7_RUS, TITLE_KOL_MF_DZ_PICKUP7_ENG},
  {TITLE_KOL_MF_DZ_PICKUP8_UKR, TITLE_KOL_MF_DZ_PICKUP8_RUS, TITLE_KOL_MF_DZ_PICKUP8_ENG},

  {TITLE_KOL_OF_DZ_PICKUP0_UKR, TITLE_KOL_OF_DZ_PICKUP0_RUS, TITLE_KOL_OF_DZ_PICKUP0_ENG},
  {TITLE_KOL_OF_DZ_PICKUP1_UKR, TITLE_KOL_OF_DZ_PICKUP1_RUS, TITLE_KOL_OF_DZ_PICKUP1_ENG},
  {TITLE_KOL_OF_DZ_PICKUP2_UKR, TITLE_KOL_OF_DZ_PICKUP2_RUS, TITLE_KOL_OF_DZ_PICKUP2_ENG},
  {TITLE_KOL_OF_DZ_PICKUP3_UKR, TITLE_KOL_OF_DZ_PICKUP3_RUS, TITLE_KOL_OF_DZ_PICKUP3_ENG},
  {TITLE_KOL_OF_DZ_PICKUP4_UKR, TITLE_KOL_OF_DZ_PICKUP4_RUS, TITLE_KOL_OF_DZ_PICKUP4_ENG},
  {TITLE_KOL_OF_DZ_PICKUP5_UKR, TITLE_KOL_OF_DZ_PICKUP5_RUS, TITLE_KOL_OF_DZ_PICKUP5_ENG},
  {TITLE_KOL_OF_DZ_PICKUP6_UKR, TITLE_KOL_OF_DZ_PICKUP6_RUS, TITLE_KOL_OF_DZ_PICKUP6_ENG},
  {TITLE_KOL_OF_DZ_PICKUP7_UKR, TITLE_KOL_OF_DZ_PICKUP7_RUS, TITLE_KOL_OF_DZ_PICKUP7_ENG},
  {TITLE_KOL_OF_DZ_PICKUP8_UKR, TITLE_KOL_OF_DZ_PICKUP8_RUS, TITLE_KOL_OF_DZ_PICKUP8_ENG}
};
const TITLE DZ_Delay_title[MAX_NUMBER_DELAY_DZ + MAX_NUMBER_DELAY_DZ_G] = 
{
  {TITLE_DZ1_DELAY0_UKR, TITLE_DZ1_DELAY0_RUS, TITLE_DZ1_DELAY0_ENG},
  {TITLE_DZ1_DELAY1_UKR, TITLE_DZ1_DELAY1_RUS, TITLE_DZ1_DELAY1_ENG},
  {TITLE_DZ1_DELAY2_UKR, TITLE_DZ1_DELAY2_RUS, TITLE_DZ1_DELAY2_ENG},

  {TITLE_DZ2_DELAY0_UKR , TITLE_DZ2_DELAY0_RUS , TITLE_DZ2_DELAY0_ENG},
  {TITLE_DZ2_DELAY1_UKR , TITLE_DZ2_DELAY1_RUS , TITLE_DZ2_DELAY1_ENG },
  {TITLE_DZ2_DELAY2_UKR , TITLE_DZ2_DELAY2_RUS , TITLE_DZ2_DELAY2_ENG },
  {TITLE_DZ2_DELAY3_UKR , TITLE_DZ2_DELAY3_RUS , TITLE_DZ2_DELAY3_ENG },
  {TITLE_DZ2_DELAY4_UKR , TITLE_DZ2_DELAY4_RUS , TITLE_DZ2_DELAY4_ENG },
  {TITLE_DZ2_DELAY5_UKR , TITLE_DZ2_DELAY5_RUS , TITLE_DZ2_DELAY5_ENG },
  {TITLE_DZ2_DELAY6_UKR , TITLE_DZ2_DELAY6_RUS , TITLE_DZ2_DELAY6_ENG },
  {TITLE_DZ2_DELAY7_UKR , TITLE_DZ2_DELAY7_RUS , TITLE_DZ2_DELAY7_ENG },
  {TITLE_DZ2_DELAY8_UKR , TITLE_DZ2_DELAY8_RUS , TITLE_DZ2_DELAY8_ENG },
  {TITLE_DZ2_DELAY9_UKR , TITLE_DZ2_DELAY9_RUS , TITLE_DZ2_DELAY9_ENG },
  {TITLE_DZ2_DELAY10_UKR, TITLE_DZ2_DELAY10_RUS, TITLE_DZ2_DELAY10_ENG},
  {TITLE_DZ2_DELAY11_UKR, TITLE_DZ2_DELAY11_RUS, TITLE_DZ2_DELAY11_ENG},
  {TITLE_DZ2_DELAY12_UKR, TITLE_DZ2_DELAY12_RUS, TITLE_DZ2_DELAY12_ENG},
  {TITLE_DZ2_DELAY13_UKR, TITLE_DZ2_DELAY13_RUS, TITLE_DZ2_DELAY13_ENG},

  {TITLE_DZ3_DELAY0_UKR , TITLE_DZ3_DELAY0_RUS , TITLE_DZ3_DELAY0_ENG},
  {TITLE_DZ3_DELAY1_UKR , TITLE_DZ3_DELAY1_RUS , TITLE_DZ3_DELAY1_ENG },
  {TITLE_DZ3_DELAY2_UKR , TITLE_DZ3_DELAY2_RUS , TITLE_DZ3_DELAY2_ENG },
  {TITLE_DZ3_DELAY3_UKR , TITLE_DZ3_DELAY3_RUS , TITLE_DZ3_DELAY3_ENG },
  {TITLE_DZ3_DELAY4_UKR , TITLE_DZ3_DELAY4_RUS , TITLE_DZ3_DELAY4_ENG },
  {TITLE_DZ3_DELAY5_UKR , TITLE_DZ3_DELAY5_RUS , TITLE_DZ3_DELAY5_ENG },
  {TITLE_DZ3_DELAY6_UKR , TITLE_DZ3_DELAY6_RUS , TITLE_DZ3_DELAY6_ENG },
  {TITLE_DZ3_DELAY7_UKR , TITLE_DZ3_DELAY7_RUS , TITLE_DZ3_DELAY7_ENG },
  {TITLE_DZ3_DELAY8_UKR , TITLE_DZ3_DELAY8_RUS , TITLE_DZ3_DELAY8_ENG },
  {TITLE_DZ3_DELAY9_UKR , TITLE_DZ3_DELAY9_RUS , TITLE_DZ3_DELAY9_ENG },
  {TITLE_DZ3_DELAY10_UKR, TITLE_DZ3_DELAY10_RUS, TITLE_DZ3_DELAY10_ENG},
  {TITLE_DZ3_DELAY11_UKR, TITLE_DZ3_DELAY11_RUS, TITLE_DZ3_DELAY11_ENG},
  {TITLE_DZ3_DELAY12_UKR, TITLE_DZ3_DELAY12_RUS, TITLE_DZ3_DELAY12_ENG},
  {TITLE_DZ3_DELAY13_UKR, TITLE_DZ3_DELAY13_RUS, TITLE_DZ3_DELAY13_ENG},

  {TITLE_DZ4_DELAY0_UKR , TITLE_DZ4_DELAY0_RUS , TITLE_DZ4_DELAY0_ENG},
  {TITLE_DZ4_DELAY1_UKR , TITLE_DZ4_DELAY1_RUS , TITLE_DZ4_DELAY1_ENG },
  {TITLE_DZ4_DELAY2_UKR , TITLE_DZ4_DELAY2_RUS , TITLE_DZ4_DELAY2_ENG },
  {TITLE_DZ4_DELAY3_UKR , TITLE_DZ4_DELAY3_RUS , TITLE_DZ4_DELAY3_ENG },
  {TITLE_DZ4_DELAY4_UKR , TITLE_DZ4_DELAY4_RUS , TITLE_DZ4_DELAY4_ENG },
  {TITLE_DZ4_DELAY5_UKR , TITLE_DZ4_DELAY5_RUS , TITLE_DZ4_DELAY5_ENG },
  {TITLE_DZ4_DELAY6_UKR , TITLE_DZ4_DELAY6_RUS , TITLE_DZ4_DELAY6_ENG },
  {TITLE_DZ4_DELAY7_UKR , TITLE_DZ4_DELAY7_RUS , TITLE_DZ4_DELAY7_ENG },
  {TITLE_DZ4_DELAY8_UKR , TITLE_DZ4_DELAY8_RUS , TITLE_DZ4_DELAY8_ENG },
  {TITLE_DZ4_DELAY9_UKR , TITLE_DZ4_DELAY9_RUS , TITLE_DZ4_DELAY9_ENG },
  {TITLE_DZ4_DELAY10_UKR, TITLE_DZ4_DELAY10_RUS, TITLE_DZ4_DELAY10_ENG},
  {TITLE_DZ4_DELAY11_UKR, TITLE_DZ4_DELAY11_RUS, TITLE_DZ4_DELAY11_ENG},
  {TITLE_DZ4_DELAY12_UKR, TITLE_DZ4_DELAY12_RUS, TITLE_DZ4_DELAY12_ENG},
  {TITLE_DZ4_DELAY13_UKR, TITLE_DZ4_DELAY13_RUS, TITLE_DZ4_DELAY13_ENG},

  {TITLE_DZ5_DELAY0_UKR , TITLE_DZ5_DELAY0_RUS , TITLE_DZ5_DELAY0_ENG},
  {TITLE_DZ5_DELAY1_UKR , TITLE_DZ5_DELAY1_RUS , TITLE_DZ5_DELAY1_ENG },
  {TITLE_DZ5_DELAY2_UKR , TITLE_DZ5_DELAY2_RUS , TITLE_DZ5_DELAY2_ENG },
  {TITLE_DZ5_DELAY3_UKR , TITLE_DZ5_DELAY3_RUS , TITLE_DZ5_DELAY3_ENG },
  {TITLE_DZ5_DELAY4_UKR , TITLE_DZ5_DELAY4_RUS , TITLE_DZ5_DELAY4_ENG },
  {TITLE_DZ5_DELAY5_UKR , TITLE_DZ5_DELAY5_RUS , TITLE_DZ5_DELAY5_ENG },
  {TITLE_DZ5_DELAY6_UKR , TITLE_DZ5_DELAY6_RUS , TITLE_DZ5_DELAY6_ENG },
  {TITLE_DZ5_DELAY7_UKR , TITLE_DZ5_DELAY7_RUS , TITLE_DZ5_DELAY7_ENG },
  {TITLE_DZ5_DELAY8_UKR , TITLE_DZ5_DELAY8_RUS , TITLE_DZ5_DELAY8_ENG },
  {TITLE_DZ5_DELAY9_UKR , TITLE_DZ5_DELAY9_RUS , TITLE_DZ5_DELAY9_ENG },
  {TITLE_DZ5_DELAY10_UKR, TITLE_DZ5_DELAY10_RUS, TITLE_DZ5_DELAY10_ENG},
  {TITLE_DZ5_DELAY11_UKR, TITLE_DZ5_DELAY11_RUS, TITLE_DZ5_DELAY11_ENG},
  {TITLE_DZ5_DELAY12_UKR, TITLE_DZ5_DELAY12_RUS, TITLE_DZ5_DELAY12_ENG},
  {TITLE_DZ5_DELAY13_UKR, TITLE_DZ5_DELAY13_RUS, TITLE_DZ5_DELAY13_ENG},
  
  {TITLE_KOL_MF_DZ_DELAY0_UKR, TITLE_KOL_MF_DZ_DELAY0_RUS, TITLE_KOL_MF_DZ_DELAY0_ENG},
  {TITLE_KOL_MF_DZ_DELAY1_UKR, TITLE_KOL_MF_DZ_DELAY1_RUS, TITLE_KOL_MF_DZ_DELAY1_ENG},
  {TITLE_KOL_MF_DZ_DELAY2_UKR, TITLE_KOL_MF_DZ_DELAY2_RUS, TITLE_KOL_MF_DZ_DELAY2_ENG},
  {TITLE_KOL_MF_DZ_DELAY3_UKR, TITLE_KOL_MF_DZ_DELAY3_RUS, TITLE_KOL_MF_DZ_DELAY3_ENG},
  
  {TITLE_KOL_OF_DZ_DELAY0_UKR, TITLE_KOL_OF_DZ_DELAY0_RUS, TITLE_KOL_OF_DZ_DELAY0_ENG},
  {TITLE_KOL_OF_DZ_DELAY1_UKR, TITLE_KOL_OF_DZ_DELAY1_RUS, TITLE_KOL_OF_DZ_DELAY1_ENG},
  {TITLE_KOL_OF_DZ_DELAY2_UKR, TITLE_KOL_OF_DZ_DELAY2_RUS, TITLE_KOL_OF_DZ_DELAY2_ENG},
  {TITLE_KOL_OF_DZ_DELAY3_UKR, TITLE_KOL_OF_DZ_DELAY3_RUS, TITLE_KOL_OF_DZ_DELAY3_ENG},

  {TITLE_DZ_G_DELAY0_UKR, TITLE_DZ_G_DELAY0_RUS, TITLE_DZ_G_DELAY0_ENG},
  {TITLE_DZ_G_DELAY1_UKR, TITLE_DZ_G_DELAY1_RUS, TITLE_DZ_G_DELAY1_ENG}
};

const TITLE DZ_State_title[MAX_NUMBER_CTRL_DZ] = 
{
  {TITLE_DZ1_STATE0_UKR, TITLE_DZ1_STATE0_RUS, TITLE_DZ1_STATE0_ENG},
  {TITLE_DZ1_STATE1_UKR, TITLE_DZ1_STATE1_RUS, TITLE_DZ1_STATE1_ENG},
  {TITLE_DZ1_STATE2_UKR, TITLE_DZ1_STATE2_RUS, TITLE_DZ1_STATE2_ENG},

  {TITLE_DZ2_STATE0_UKR, TITLE_DZ2_STATE0_RUS, TITLE_DZ2_STATE0_ENG},
  {TITLE_DZ2_STATE1_UKR, TITLE_DZ2_STATE1_RUS, TITLE_DZ2_STATE1_ENG},
  {TITLE_DZ2_STATE2_UKR, TITLE_DZ2_STATE2_RUS, TITLE_DZ2_STATE2_ENG},
  {TITLE_DZ2_STATE3_UKR, TITLE_DZ2_STATE3_RUS, TITLE_DZ2_STATE3_ENG},
  {TITLE_DZ2_STATE4_UKR, TITLE_DZ2_STATE4_RUS, TITLE_DZ2_STATE4_ENG},
  {TITLE_DZ2_STATE5_UKR, TITLE_DZ2_STATE5_RUS, TITLE_DZ2_STATE5_ENG},

  {TITLE_DZ3_STATE0_UKR, TITLE_DZ3_STATE0_RUS, TITLE_DZ3_STATE0_ENG},
  {TITLE_DZ3_STATE1_UKR, TITLE_DZ3_STATE1_RUS, TITLE_DZ3_STATE1_ENG},
  {TITLE_DZ3_STATE2_UKR, TITLE_DZ3_STATE2_RUS, TITLE_DZ3_STATE2_ENG},
  {TITLE_DZ3_STATE3_UKR, TITLE_DZ3_STATE3_RUS, TITLE_DZ3_STATE3_ENG},
  {TITLE_DZ3_STATE4_UKR, TITLE_DZ3_STATE4_RUS, TITLE_DZ3_STATE4_ENG},
  {TITLE_DZ3_STATE5_UKR, TITLE_DZ3_STATE5_RUS, TITLE_DZ3_STATE5_ENG},

  {TITLE_DZ4_STATE0_UKR, TITLE_DZ4_STATE0_RUS, TITLE_DZ4_STATE0_ENG},
  {TITLE_DZ4_STATE1_UKR, TITLE_DZ4_STATE1_RUS, TITLE_DZ4_STATE1_ENG},
  {TITLE_DZ4_STATE2_UKR, TITLE_DZ4_STATE2_RUS, TITLE_DZ4_STATE2_ENG},
  {TITLE_DZ4_STATE3_UKR, TITLE_DZ4_STATE3_RUS, TITLE_DZ4_STATE3_ENG},
  {TITLE_DZ4_STATE4_UKR, TITLE_DZ4_STATE4_RUS, TITLE_DZ4_STATE4_ENG},
  {TITLE_DZ4_STATE5_UKR, TITLE_DZ4_STATE5_RUS, TITLE_DZ4_STATE5_ENG},

  {TITLE_DZ5_STATE0_UKR, TITLE_DZ5_STATE0_RUS, TITLE_DZ5_STATE0_ENG},
  {TITLE_DZ5_STATE1_UKR, TITLE_DZ5_STATE1_RUS, TITLE_DZ5_STATE1_ENG},
  {TITLE_DZ5_STATE2_UKR, TITLE_DZ5_STATE2_RUS, TITLE_DZ5_STATE2_ENG},
  {TITLE_DZ5_STATE3_UKR, TITLE_DZ5_STATE3_RUS, TITLE_DZ5_STATE3_ENG},
  {TITLE_DZ5_STATE4_UKR, TITLE_DZ5_STATE4_RUS, TITLE_DZ5_STATE4_ENG},
  {TITLE_DZ5_STATE5_UKR, TITLE_DZ5_STATE5_RUS, TITLE_DZ5_STATE5_ENG},

  {TITLE_DZ_STATE0_UKR , TITLE_DZ_STATE0_RUS , TITLE_DZ_STATE0_ENG }
};
int DZ_select_group = 0;

WM_HWIN CB_FrameWin = WM_UNATTACHED, CB_MultiPage_groups, CB_Window_group, CB_MultiPage_type_info, CB_Pages[MAX_PAGES_PROTECTION_SDC];
SCROLLBAR_Handle ScrollBar_CB_Pages[MAX_PAGES_PROTECTION_SDC];
int _y_cbPickup_CB = 0, _y_cbDelay_CB = 0, _y_cbDelay_CB_g = 0, _y_cbControl_CB = 0;
WM_HWIN CB_Pickup_t[MAX_NUMBER_PICKUP_CB], CB_Pickup_v[MAX_NUMBER_PICKUP_CB], CB_Pickup_m[MAX_NUMBER_PICKUP_CB];
WM_HWIN CB_Delay_t[MAX_NUMBER_DELAY_CB], CB_Delay_v[MAX_NUMBER_DELAY_CB], CB_Delay_m[MAX_NUMBER_DELAY_CB];
WM_HWIN CB_State_t[MAX_NUMBER_CTRL_CB], CB_State_v[MAX_NUMBER_CTRL_CB];
const unsigned short int nalashtuvannja_CB[1] = {MAX_NUMBER_CTRL_CB_G};

const TITLE CB_panel_title = {TITLE_CB_PANEL_UKR, TITLE_CB_PANEL_RUS, TITLE_CB_PANEL_ENG};

const TITLE CB_Pickup_title[MAX_NUMBER_PICKUP_CB] = 
{
  {TITLE_CB_PICKUP0_UKR , TITLE_CB_PICKUP0_RUS , TITLE_CB_PICKUP0_ENG },
  {TITLE_CB_PICKUP1_UKR , TITLE_CB_PICKUP1_RUS , TITLE_CB_PICKUP1_ENG },
  {TITLE_CB_PICKUP2_UKR , TITLE_CB_PICKUP2_RUS , TITLE_CB_PICKUP2_ENG },
  {TITLE_CB_PICKUP3_UKR , TITLE_CB_PICKUP3_RUS , TITLE_CB_PICKUP3_ENG },
  {TITLE_CB_PICKUP4_UKR , TITLE_CB_PICKUP4_RUS , TITLE_CB_PICKUP4_ENG },
  {TITLE_CB_PICKUP5_UKR , TITLE_CB_PICKUP5_RUS , TITLE_CB_PICKUP5_ENG },
  {TITLE_CB_PICKUP6_UKR , TITLE_CB_PICKUP6_RUS , TITLE_CB_PICKUP6_ENG }
};
const TITLE CB_Delay_title[MAX_NUMBER_DELAY_CB] = 
{
  {TITLE_CB_DELAY0_UKR, TITLE_CB_DELAY0_RUS, TITLE_CB_DELAY0_ENG},
  {TITLE_CB_DELAY1_UKR, TITLE_CB_DELAY1_RUS, TITLE_CB_DELAY1_ENG},
  {TITLE_CB_DELAY2_UKR, TITLE_CB_DELAY2_RUS, TITLE_CB_DELAY2_ENG},
  {TITLE_CB_DELAY3_UKR, TITLE_CB_DELAY3_RUS, TITLE_CB_DELAY3_ENG},
  {TITLE_CB_DELAY4_UKR, TITLE_CB_DELAY4_RUS, TITLE_CB_DELAY4_ENG}
};

const TITLE CB_State_title[MAX_NUMBER_CTRL_CB] = 
{
  {TITLE_CB_STATE0_UKR, TITLE_CB_STATE0_RUS, TITLE_CB_STATE0_ENG},
  {TITLE_CB_STATE1_UKR, TITLE_CB_STATE1_RUS, TITLE_CB_STATE1_ENG},
  {TITLE_CB_STATE2_UKR, TITLE_CB_STATE2_RUS, TITLE_CB_STATE2_ENG},
  {TITLE_CB_STATE3_UKR, TITLE_CB_STATE3_RUS, TITLE_CB_STATE3_ENG}
};

int one_group = 0;

WM_HWIN Settings_IconView = WM_UNATTACHED;
BITMAP_ITEM _aBitmapItem_settings[SETTINGS_SIZE] = 
{
  {&bmConfiguration, {CONF_UKR_TXT       , CONF_RUS_TXT       , CONF_ENG_TXT       }, {EXPL_CONF_IT_UKR       , EXPL_CONF_IT_RUS       , EXPL_CONF_IT_ENG       }},
  {&bmRanking      , {RANK_UKR_TXT       , RANK_RUS_TXT       , RANK_ENG_TXT       }, {EXPL_RANK_IT_UKR       , EXPL_RANK_IT_RUS       , EXPL_RANK_IT_ENG       }},
  {&bmOn_DZ        , {DZ_UKR_TXT         , DZ_RUS_TXT         , DZ_ENG_TXT         }, {EXPL_DZ_IT_UKR         , EXPL_DZ_IT_RUS         , EXPL_DZ_IT_ENG         }},
  {&bmOn_MTZ       , {MTZ_UKR_TXT        ,  MTZ_RUS_TXT       ,  MTZ_ENG_TXT       }, {EXPL_MTZ_IT_UKR        , EXPL_MTZ_IT_RUS        ,  EXPL_MTZ_IT_ENG       }},
  {&bmOn_TZNP      , {TZNP_UKR_TXT       , TZNP_RUS_TXT       , TZNP_ENG_TXT       }, {EXPL_TZNP_IT_UKR       , EXPL_TZNP_IT_RUS       , EXPL_TZNP_IT_ENG       }},
  {&bmOn_ZOP       , {ZOP_UKR_TXT        , ZOP_RUS_TXT        , ZOP_ENG_TXT        }, {EXPL_ZOP_IT_UKR        , EXPL_ZOP_IT_RUS        , EXPL_ZOP_IT_ENG        }},
  {&bmOn_Umin      , {UMIN_UKR_TXT       , UMIN_RUS_TXT       , UMIN_ENG_TXT       }, {EXPL_UMIN_IT_UKR       , EXPL_UMIN_IT_RUS       , EXPL_UMIN_IT_ENG       }},
  {&bmOn_Umax      , {UMAX_UKR_TXT       , UMAX_RUS_TXT       , UMAX_ENG_TXT       }, {EXPL_UMAX_IT_UKR       , EXPL_UMAX_IT_RUS       , EXPL_UMAX_IT_ENG       }},
  {&bmOn_APV       , {APV_UKR_TXT        , APV_RUS_TXT        , APV_ENG_TXT        }, {EXPL_APV_IT_UKR        , EXPL_APV_IT_RUS        , EXPL_APV_IT_ENG        }},
  {&bmOn_UROV      , {UROV_UKR_TXT       , UROV_RUS_TXT       , UROV_ENG_TXT       }, {EXPL_UROV_IT_UKR       , EXPL_UROV_IT_RUS       , EXPL_UROV_IT_ENG       }},
  {&bmOn_CB        , {CB_UKR_TXT         , CB_RUS_TXT         , CB_ENG_TXT         }, {EXPL_CB_IT_UKR         , EXPL_CB_IT_RUS         , EXPL_CB_IT_ENG         }},
  {&bmTransformer  , {TRANSFORMER_UKR_TXT, TRANSFORMER_RUS_TXT, TRANSFORMER_ENG_TXT}, {EXPL_TRANSFORMER_IT_UKR, EXPL_TRANSFORMER_IT_RUS, EXPL_TRANSFORMER_IT_ENG}},
  {&bmComm         , {COMM_UKR_TXT       , COMM_RUS_TXT       , COMM_ENG_TXT       }, {EXPL_COMM_IT_UKR       , EXPL_COMM_IT_RUS       , EXPL_COMM_IT_ENG       }}
};

const GUI_BITMAP * pBitmaps_prt_off[SETTINGS_SIZE - 4] = {&bmOff_DZ, &bmOff_MTZ, &bmOff_TZNP, &bmOff_ZOP, &bmOff_Umin, &bmOff_Umax, &bmOff_APV, &bmOff_UROV};


WM_HWIN Comm_IconView = WM_UNATTACHED;
BITMAP_ITEM _aBitmapItem_Comm[COMM_SIZE] = 
{
  {&bmModbus, {MODBUS_UKR_TXT, MODBUS_RUS_TXT, MODBUS_ENG_TXT}, {EXPL_MODBUS_IT_UKR, EXPL_MODBUS_IT_RUS, EXPL_MODBUS_IT_ENG}},
  {&bmNet   , {NET_UKR_TXT   , NET_RUS_TXT   , NET_ENG_TXT   }, {EXPL_NET_IT_UKR   , EXPL_NET_IT_RUS   , EXPL_NET_IT_ENG   }}
};

WM_HMEM Edit_groups = WM_UNATTACHED, Edit_saving_EERPOM = WM_UNATTACHED, Edit_transmit_settings_L = WM_UNATTACHED, Edit_transmit_settings_M = WM_UNATTACHED, Edit_clock = WM_UNATTACHED;
unsigned int redraw_status_bar = 1;

WM_HWIN Modbus_FrameWin = WM_UNATTACHED;
const TITLE Modbus_panel_title = {TITLE_MODBUS_PANEL_UKR, TITLE_MODBUS_PANEL_RUS, TITLE_MODBUS_PANEL_ENG};
SCROLLBAR_Handle ScrollBar_Modbus;
int _y_cbPickup_Modbus = 0;
WM_HWIN Modbus_t[MAX_NUMBER_ITEMS_MODBUS];
WM_HWIN Modbus_v[MAX_NUMBER_ITEMS_MODBUS];
WM_HWIN Modbus_d;
const TITLE Modbus_title[MAX_NUMBER_ITEMS_MODBUS] = 
{
  {TITLE_MODBUS0_UKR , TITLE_MODBUS0_RUS , TITLE_MODBUS0_ENG },
  {TITLE_MODBUS1_UKR , TITLE_MODBUS1_RUS , TITLE_MODBUS1_ENG },
  {TITLE_MODBUS2_UKR , TITLE_MODBUS2_RUS , TITLE_MODBUS2_ENG },
  {TITLE_MODBUS3_UKR , TITLE_MODBUS3_RUS , TITLE_MODBUS3_ENG },
  {TITLE_MODBUS4_UKR , TITLE_MODBUS4_RUS , TITLE_MODBUS4_ENG }
};
const char *Baud_rate_title[7] = {"115200", "57600", "38400", "28800", "19200", "14400", "9600"};
const TITLE Parity_title[3] = 
{
  {"Нема"  , "Нет"    , "None" },
  {"Непарн.", "Нечет.", "Odd " },
  {"Парн." , "Чет."   , "Even" }
};
const char *Stop_bits_title[2] = {"1", "2"};
const TITLE Modbus_Timeout_dimention = {"симв.", "симв.", "symb."};

WM_HWIN Net_FrameWin = WM_UNATTACHED;
const TITLE Net_panel_title = {TITLE_NET_PANEL_UKR, TITLE_NET_PANEL_RUS, TITLE_NET_PANEL_ENG};
SCROLLBAR_Handle ScrollBar_Net;
int _y_cbPickup_Net = 0;

WM_HWIN Transformer_FrameWin = WM_UNATTACHED;
const TITLE Transformer_panel_title = {TITLE_TRANSFORMER_PANEL_UKR, TITLE_TRANSFORMER_PANEL_RUS, TITLE_TRANSFORMER_PANEL_ENG};
SCROLLBAR_Handle ScrollBar_Transformer;
int _y_cbPickup_Transformer = 0;
WM_HWIN Transformer_t[MAX_NUMBER_ITEMS_TRANSFORMER];
WM_HWIN Transformer_v[MAX_NUMBER_ITEMS_TRANSFORMER];
const TITLE Transformer_title[MAX_NUMBER_ITEMS_TRANSFORMER] = 
{
  {TITLE_TRANSFORMER0_UKR , TITLE_TRANSFORMER0_RUS , TITLE_TRANSFORMER0_ENG },
  {TITLE_TRANSFORMER1_UKR , TITLE_TRANSFORMER1_RUS , TITLE_TRANSFORMER1_ENG },
  {TITLE_TRANSFORMER2_UKR , TITLE_TRANSFORMER2_RUS , TITLE_TRANSFORMER2_ENG }
};

WM_HWIN Clock_FrameWin = WM_UNATTACHED;
const TITLE Clock_panel_title = {TITLE_CLOCK_PANEL_UKR, TITLE_CLOCK_PANEL_RUS, TITLE_CLOCK_PANEL_ENG};
WM_HWIN Clock_t[5];
WM_HWIN Clock_v[MAX_NUMBER_ITEMS_CLOCK];
const char *Calibration_title[3] = {TITLE_CLOCK0_UKR, TITLE_CLOCK0_RUS, TITLE_CLOCK0_ENG};
const TITLE Transformer_line_title[3] = 
{
  {TITLE_TRANSFORMER_LINE0_UKR, TITLE_TRANSFORMER_LINE0_RUS, TITLE_TRANSFORMER_LINE0_ENG},
  {TITLE_TRANSFORMER_LINE1_UKR, TITLE_TRANSFORMER_LINE1_RUS, TITLE_TRANSFORMER_LINE1_ENG},
  {TITLE_TRANSFORMER_LINE2_UKR, TITLE_TRANSFORMER_LINE2_RUS, TITLE_TRANSFORMER_LINE2_ENG}
};

WM_HWIN Resurs_FrameWin = WM_UNATTACHED, Resurs_t[MAX_NUMBER_ITEMS_RESURS], Resurs_v[MAX_NUMBER_ITEMS_RESURS];
const TITLE Resurs_panel_title = {TITLE_RESURS_PANEL_UKR, TITLE_RESURS_PANEL_RUS, TITLE_RESURS_PANEL_ENG};
const TITLE Resurs_title[MAX_NUMBER_ITEMS_RESURS] = 
{
  {TITLE_RESURS0_UKR , TITLE_RESURS0_RUS , TITLE_RESURS0_ENG },
  {TITLE_RESURS1_UKR , TITLE_RESURS1_RUS , TITLE_RESURS1_ENG }
};
unsigned int resurs_tmp, resurs_count_tmp;

WM_HWIN LCD_Settings_FrameWin = WM_UNATTACHED, LCD_Settings_Edit, LCD_Settings_t, LCD_Settings_d;
const TITLE LCD_Settings_title = {TITLE_LCD_SETTINGS_UKR, TITLE_LCD_SETTINGS_RUS, TITLE_LCD_SETTINGS_ENG};
const TITLE LCD_Settings_Delay_title = {TITLE_LCD_SETTINGS_DELAY_UKR, TITLE_LCD_SETTINGS_DELAY_RUS, TITLE_LCD_SETTINGS_DELAY_ENG};
const TITLE LCD_Settings_Delay_dimention = {"хв.", "мин.", "min."};

WM_HWIN TM_FrameWin = WM_UNATTACHED, TM_MultiPage_type_info, TM_Pages[2], TM_IO_Header, TM_IO_Pages[2], TM_F_Header, TM_F_Pages[2];
const TITLE TM_panel_title = {TITLE_TM_PANEL_UKR, TITLE_TM_PANEL_RUS, TITLE_TM_PANEL_ENG};
const LANG_ITEM TM_Page_name[] = 
{
  { {TITLE_TM_PAGE_1_UKR, TITLE_TM_PAGE_1_RUS, TITLE_TM_PAGE_1_ENG}, {EXPL_TM_PAGE_1_UKR, EXPL_TM_PAGE_1_RUS, EXPL_TM_PAGE_1_ENG} },
  { {TITLE_TM_PAGE_2_UKR, TITLE_TM_PAGE_2_RUS, TITLE_TM_PAGE_2_ENG}, {EXPL_TM_PAGE_2_UKR, EXPL_TM_PAGE_2_RUS, EXPL_TM_PAGE_2_ENG} }
};
const TITLE TM_IO_columns[] = 
{
  {TITLE_TM_IO_COLUMN_1_UKR, TITLE_TM_IO_COLUMN_1_RUS, TITLE_TM_IO_COLUMN_1_ENG},
  {TITLE_TM_IO_COLUMN_2_UKR, TITLE_TM_IO_COLUMN_2_RUS, TITLE_TM_IO_COLUMN_2_ENG}
};
const TITLE TM_F_columns[] = 
{
  {TITLE_TM_F_COLUMN_1_UKR, TITLE_TM_F_COLUMN_1_RUS, TITLE_TM_F_COLUMN_1_ENG},
  {TITLE_TM_F_COLUMN_2_UKR, TITLE_TM_F_COLUMN_2_RUS, TITLE_TM_F_COLUMN_2_ENG}
};
SCROLLBAR_Handle ScrollBar_TM_Pages[2];
WM_HWIN TM_Inputs[NUM_IN], TM_Outputs[NUM_OUT];
WM_HWIN TM_F[2][MAX_NUMBER_F_IN_PANEL];
unsigned int TM_max_number_bits = 0;

unsigned int state_active_functions[NUMBER_4BYTES_WORDS_FOR_FUBCTIOBS];
unsigned int state_actuated_functions[NUMBER_4BYTES_WORDS_FOR_FUBCTIOBS];

WM_HWIN Diagnostics_FrameWin = WM_UNATTACHED, Diagnostics_MultiPage_type_info, Diagnostics_Pages;
const TITLE Diagnostics_panel_title = {TITLE_DIAGNOSTICS_PANEL_UKR, TITLE_DIAGNOSTICS_PANEL_RUS, TITLE_DIAGNOSTICS_PANEL_ENG};
const LANG_ITEM Diagnostics_Page_name[] = 
{
  { {TITLE_DIAGNOSTICS_PAGE_1_UKR, TITLE_DIAGNOSTICS_PAGE_1_RUS, TITLE_DIAGNOSTICS_PAGE_1_ENG}, {EXPL_DIAGNOSTICS_PAGE_1_UKR, EXPL_DIAGNOSTICS_PAGE_1_RUS, EXPL_DIAGNOSTICS_PAGE_1_ENG} },
  { {TITLE_DIAGNOSTICS_PAGE_2_UKR, TITLE_DIAGNOSTICS_PAGE_2_RUS, TITLE_DIAGNOSTICS_PAGE_2_ENG}, {EXPL_DIAGNOSTICS_PAGE_2_UKR, EXPL_DIAGNOSTICS_PAGE_2_RUS, EXPL_DIAGNOSTICS_PAGE_2_ENG} },
  { {TITLE_DIAGNOSTICS_PAGE_3_UKR, TITLE_DIAGNOSTICS_PAGE_3_RUS, TITLE_DIAGNOSTICS_PAGE_3_ENG}, {EXPL_DIAGNOSTICS_PAGE_3_UKR, EXPL_DIAGNOSTICS_PAGE_3_RUS, EXPL_DIAGNOSTICS_PAGE_3_ENG} }
};
SCROLLBAR_Handle ScrollBar_Diagnostics_Pages;
WM_HWIN Diagnostics_Info[MAX_NUMBER_DIAGN_IN_PANEL];
unsigned int Diagnistics_max_number_bits[3] = {0, 0, 0};

char *diagnostics_bs_mrzv_str_tmp[LANG_LIST_SIZE][ALL_NUMB_DIAGNOSTICS] = 
{
  DIAGN_BS_MRZV_UKR_NAME_LIST, DIAGN_BS_MRZV_RUS_NAME_LIST, DIAGN_BS_MRZV_ENG_NAME_LIST
};
char *diagnostics_bo_mrzv_m_str_tmp[LANG_LIST_SIZE][ALL_NUMB_DIAGNOSTICS] = 
{
  DIAGN_BO_MRZV_M_UKR_NAME_LIST, DIAGN_BO_MRZV_M_RUS_NAME_LIST, DIAGN_BO_MRZV_M_ENG_NAME_LIST
};
char *diagnostics_bo_mrzv_l_str_tmp[LANG_LIST_SIZE][ALL_NUMB_DIAGNOSTICS] = 
{
  DIAGN_BO_MRZV_L_UKR_NAME_LIST, DIAGN_BO_MRZV_L_RUS_NAME_LIST, DIAGN_BO_MRZV_L_ENG_NAME_LIST
};

unsigned int diagnostics_bs_mrzv_tmp[NUMBER_4BYTES_WORDS_FOR_DIAGNOSTICS];
unsigned int diagnostics_bo_mrzv_m_tmp[NUMBER_4BYTES_WORDS_FOR_DIAGNOSTICS];
unsigned int diagnostics_bo_mrzv_l_tmp[NUMBER_4BYTES_WORDS_FOR_DIAGNOSTICS];

MENU_Handle hMenu_main, hMin_settings, hOption, hPasswords, hPickup_Group, hCommands, hAbout;
const TITLE menu_option_title[] = 
{
  {TITLE_MENU_MIN_SETTINGS_UKR, TITLE_MENU_MIN_SETTINGS_RUS, TITLE_MENU_MIN_SETTINGS_ENG},
    {TITLE_MENU_MIN_SETTINGS_PRT_UKR, TITLE_MENU_MIN_SETTINGS_PRT_RUS, TITLE_MENU_MIN_SETTINGS_PRT_ENG},
    {TITLE_MENU_MIN_SETTINGS_1_UKR, TITLE_MENU_MIN_SETTINGS_1_RUS, TITLE_MENU_MIN_SETTINGS_1_ENG},
    
  {TITLE_MENU_OPTION_UKR, TITLE_MENU_OPTION_RUS, TITLE_MENU_OPTION_ENG},
    {LANG_UKR_TXT, LANG_RUS_TXT, LANG_ENG_TXT},
    {TITLE_MENU_OPTION_LCD_UKR, TITLE_MENU_OPTION_LCD_RUS, TITLE_MENU_OPTION_LCD_ENG},
    {TITLE_MENU_OPTION_PASSWORDS_UKR, TITLE_MENU_OPTION_PASSWORDS_RUS, TITLE_MENU_OPTION_PASSWORDS_ENG},
      {TITLE_MENU_OPTION_PASSWORD1_UKR, TITLE_MENU_OPTION_PASSWORD1_RUS, TITLE_MENU_OPTION_PASSWORD1_ENG},
      {TITLE_MENU_OPTION_PASSWORD2_UKR, TITLE_MENU_OPTION_PASSWORD2_RUS, TITLE_MENU_OPTION_PASSWORD2_ENG},

  {TITLE_MENU_GROUPS_UKR, TITLE_MENU_GROUPS_RUS, TITLE_MENU_GROUPS_ENG},
    {TITLE_MENU_GROUPS_1_UKR, TITLE_MENU_GROUPS_1_RUS, TITLE_MENU_GROUPS_1_ENG},
    {TITLE_MENU_GROUPS_2_UKR, TITLE_MENU_GROUPS_2_RUS, TITLE_MENU_GROUPS_2_ENG},
    {TITLE_MENU_GROUPS_3_UKR, TITLE_MENU_GROUPS_3_RUS, TITLE_MENU_GROUPS_3_ENG},
    {TITLE_MENU_GROUPS_4_UKR, TITLE_MENU_GROUPS_4_RUS, TITLE_MENU_GROUPS_4_ENG},

  {TITLE_MENU_COMMANDS_UKR, TITLE_MENU_COMMANDS_RUS, TITLE_MENU_COMMANDS_ENG},
    {TITLE_MENU_COMMANDS_1_UKR, TITLE_MENU_COMMANDS_1_RUS, TITLE_MENU_COMMANDS_1_ENG},
    {TITLE_MENU_COMMANDS_2_UKR, TITLE_MENU_COMMANDS_2_RUS, TITLE_MENU_COMMANDS_2_ENG},
    {TITLE_MENU_COMMANDS_3_UKR, TITLE_MENU_COMMANDS_3_RUS, TITLE_MENU_COMMANDS_3_ENG},
    {TITLE_MENU_COMMANDS_4_UKR, TITLE_MENU_COMMANDS_4_RUS, TITLE_MENU_COMMANDS_4_ENG},
    {TITLE_MENU_COMMANDS_5_UKR, TITLE_MENU_COMMANDS_5_RUS, TITLE_MENU_COMMANDS_5_ENG},

  {TITLE_MENU_ABOUT_UKR, TITLE_MENU_ABOUT_RUS, TITLE_MENU_ABOUT_ENG},
    {TITLE_MENU_ABOUT_1_UKR, TITLE_MENU_ABOUT_1_RUS, TITLE_MENU_ABOUT_1_ENG},
};
const TITLE menu_option_explanation[] = 
{
  {EXPLANATION_MENU_MIN_SETTINGS_UKR, EXPLANATION_MENU_MIN_SETTINGS_RUS, EXPLANATION_MENU_MIN_SETTINGS_ENG},
    {EXPLANATION_MENU_MIN_SETTINGS_PRT_UKR, EXPLANATION_MENU_MIN_SETTINGS_PRT_RUS, EXPLANATION_MENU_MIN_SETTINGS_PRT_ENG},
    {EXPLANATION_MENU_MIN_SETTINGS_1_UKR, EXPLANATION_MENU_MIN_SETTINGS_1_RUS, EXPLANATION_MENU_MIN_SETTINGS_1_ENG},
    
  {EXPLANATION_MENU_OPTION_UKR, EXPLANATION_MENU_OPTION_RUS, EXPLANATION_MENU_OPTION_ENG},
    {EXPL_LANG_IT_UKR, EXPL_LANG_IT_RUS, EXPL_LANG_IT_ENG},
    {EXPLANATION_MENU_OPTION_LCD_UKR, EXPLANATION_MENU_OPTION_LCD_RUS, EXPLANATION_MENU_OPTION_LCD_ENG},
    {EXPLANATION_MENU_OPTION_PASSWORDS_UKR, EXPLANATION_MENU_OPTION_PASSWORDS_RUS, EXPLANATION_MENU_OPTION_PASSWORDS_ENG},
      {EXPLANATION_MENU_OPTION_PASSWORD1_UKR, EXPLANATION_MENU_OPTION_PASSWORD1_RUS, EXPLANATION_MENU_OPTION_PASSWORD1_ENG},
      {EXPLANATION_MENU_OPTION_PASSWORD2_UKR, EXPLANATION_MENU_OPTION_PASSWORD2_RUS, EXPLANATION_MENU_OPTION_PASSWORD2_ENG},

  {EXPLANATION_MENU_GROUPS_UKR, EXPLANATION_MENU_GROUPS_RUS, EXPLANATION_MENU_GROUPS_ENG},
    {EXPLANATION_MENU_GROUPS_1_UKR, EXPLANATION_MENU_GROUPS_1_RUS, EXPLANATION_MENU_GROUPS_1_ENG},
    {EXPLANATION_MENU_GROUPS_2_UKR, EXPLANATION_MENU_GROUPS_2_RUS, EXPLANATION_MENU_GROUPS_2_ENG},
    {EXPLANATION_MENU_GROUPS_3_UKR, EXPLANATION_MENU_GROUPS_3_RUS, EXPLANATION_MENU_GROUPS_3_ENG},
    {EXPLANATION_MENU_GROUPS_4_UKR, EXPLANATION_MENU_GROUPS_4_RUS, EXPLANATION_MENU_GROUPS_4_ENG},

  {EXPLANATION_MENU_COMMANDS_UKR, EXPLANATION_MENU_COMMANDS_RUS, EXPLANATION_MENU_COMMANDS_ENG},
    {EXPLANATION_MENU_COMMANDS_1_UKR, EXPLANATION_MENU_COMMANDS_1_RUS, EXPLANATION_MENU_COMMANDS_1_ENG},
    {EXPLANATION_MENU_COMMANDS_2_UKR, EXPLANATION_MENU_COMMANDS_2_RUS, EXPLANATION_MENU_COMMANDS_2_ENG},
    {EXPLANATION_MENU_COMMANDS_3_UKR, EXPLANATION_MENU_COMMANDS_3_RUS, EXPLANATION_MENU_COMMANDS_3_ENG},
    {EXPLANATION_MENU_COMMANDS_4_UKR, EXPLANATION_MENU_COMMANDS_4_RUS, EXPLANATION_MENU_COMMANDS_4_ENG},
    {EXPLANATION_MENU_COMMANDS_5_UKR, EXPLANATION_MENU_COMMANDS_5_RUS, EXPLANATION_MENU_COMMANDS_5_ENG},

  {EXPLANATION_MENU_ABOUT_UKR, EXPLANATION_MENU_ABOUT_RUS, EXPLANATION_MENU_ABOUT_ENG},
    {EXPLANATION_MENU_ABOUT_1_UKR, EXPLANATION_MENU_ABOUT_1_RUS, EXPLANATION_MENU_ABOUT_1_ENG},
};
const _id_user_widget id_menu[] =
{
  ID_MENU_MIN_SETTINGS,
    ID_MENU_MIN_SETTINGS_PRT,
    ID_MENU_MIN_SETTINGS_1,

    ID_MENU_OPTION,
    ID_MENU_OPTION_LANGUAGE,
    ID_MENU_OPTION_LCD,
    ID_MENU_OPTION_PASSWORDS,
      ID_MENU_OPTION_PASSWORD1,
      ID_MENU_OPTION_PASSWORD2,

  ID_MENU_GROUPS,
    ID_MENU_GROUPS_1,
    ID_MENU_GROUPS_2,
    ID_MENU_GROUPS_3,
    ID_MENU_GROUPS_4,

  ID_MENU_COMMANDS,
    ID_MENU_COMMANDS_1,
    ID_MENU_COMMANDS_2,
    ID_MENU_COMMANDS_3,
    ID_MENU_COMMANDS_4,
    ID_MENU_COMMANDS_5,

  ID_MENU_ABOUT,
    ID_MENU_ABOUT_1,
};

unsigned int current_modal_form = false;
unsigned int command_from_menu = 0;
unsigned int min_settings = false, min_settings_1 = false;

unsigned int timeout_LCD = 0;
unsigned int state_command_power_LCD = (1 << 0);//Komanda na vvimknennja

unsigned int edit_Pick_up_Set, set_new_Pick_up_Set = false;

WM_HWIN About_FrameWin = WM_UNATTACHED, About_Line_1, About_Line_2, About_Line_3, About_Line_4, About_Line_5;
WM_HWIN About_Line_6, About_Line_7, About_Line_8, About_Line_9, About_Line_10, About_Line_11, About_Line_12;
IMAGE_Handle Image_logo;
const TITLE About_title = {TITLE_MENU_ABOUT_UKR, TITLE_MENU_ABOUT_RUS, TITLE_MENU_ABOUT_ENG};

WM_HWIN Registrators_FrameWin = WM_UNATTACHED, Registrators_MultiPage_type, Registrators_Window;
WM_HWIN Registrators_Window_up, Registrators_Window_down, Registrators_Window_up_left, Registrators_Window_up_right;
WM_HWIN Registrator_number, Registrator_number_from, Registrator_total_number;
WM_HWIN Registrator_date_time_prefault, Registrator_date_time_fault;
const TITLE Registrators_panel_title = {TITLE_REGISTRATORS_PANEL_UKR, TITLE_REGISTRATORS_PANEL_RUS, TITLE_REGISTRATORS_PANEL_ENG};
const LANG_ITEM Registrators_MultiPage_Items[3] = 
{
  { {REGISTRATORS_TYPE_1_UKR  , REGISTRATORS_TYPE_1_RUS  , REGISTRATORS_TYPE_1_ENG  } , {EXPL_REGISTRATORS_TYPE_1_UKR  , EXPL_REGISTRATORS_TYPE_1_RUS  , EXPL_REGISTRATORS_TYPE_1_ENG  } },
  { {REGISTRATORS_TYPE_2_UKR  , REGISTRATORS_TYPE_2_RUS  , REGISTRATORS_TYPE_2_ENG  } , {EXPL_REGISTRATORS_TYPE_2_UKR  , EXPL_REGISTRATORS_TYPE_2_RUS  , EXPL_REGISTRATORS_TYPE_2_ENG  } },
  { {REGISTRATORS_TYPE_3_UKR  , REGISTRATORS_TYPE_3_RUS  , REGISTRATORS_TYPE_3_ENG  } , {EXPL_REGISTRATORS_TYPE_3_UKR  , EXPL_REGISTRATORS_TYPE_3_RUS  , EXPL_REGISTRATORS_TYPE_3_ENG  } }
};

//Змінні для визначеня ресурсу процесора-програми
volatile unsigned int restart_resurs_count = 0;
unsigned int resurs_temp = 0;
unsigned int resurs_global = 0;
unsigned int resurs_global_min;
unsigned int resurs_global_max = 0;

unsigned int restart_timing_period = 0;
volatile unsigned int time_period = 0;
unsigned int time_1_period = 0;
unsigned int time_2_period = 0;
unsigned int time_delta_period = 0;
unsigned int time_delta_period_min = 0xffffffff;
unsigned int time_delta_period_max = 0;

unsigned int period_10ms = false;

//Тестові біти
//Pin pPins_test[1] = {PIN_TEST};

unsigned char receiving_buffer_ZigBee[SIZE_BUFFER_ZIGBEE];
unsigned char count_receiving_byte_ZigBee = 0;
unsigned char transmiting_buffer_ZigBee[SIZE_BUFFER_ZIGBEE];
unsigned char count_transmiting_byte_ZigBee = 0;
unsigned char data_ZigBee_received = false;
unsigned char data_ZigBee_transmiting = false;

CfgTblDsc edit_settings;
AuxCfgTbl1Dsc edit_settings_1;

//__root const unsigned char gaps_data[63281];

//Обмін через SPI1
unsigned char Temporaty_SPI1_Buffer_Tx[SIZE_BUFFER_FOR_RED];
unsigned char Temporaty_SPI1_Buffer_Rx[SIZE_BUFFER_FOR_RED];
DDR2_B3_DATA unsigned int Temporaty_SPI1_Buffer_Tx_with_CS[SIZE_BUFFER_FOR_RED];
DDR2_B3_DATA unsigned int Temporaty_SPI1_Buffer_Rx_with_CS[SIZE_BUFFER_FOR_RED];
unsigned int number_transmit_SPI1 = 0;
int state_execution_spi1 = -1; //-1 - драйвер готовий до початку нових транзакцій; 0 - відбувається обмін; 1 - обмін завершений без помилок
unsigned int control_spi1_taskes[2] = {0,0};
unsigned int comparison_writing = 0; /*очищений біт означає, що іде зчитування у робочий об'єкт, встановлений біт означає що іде порівняння записаної інформації після операції запису*/
unsigned int state_spi1_task = STATE_FIRST_READING_RTC;
int etap_reset_of_bit = ETAP_CLEAR_OF_NONE;
int etap_settings_test_frequency = -1;
int etap_eeprom_write_enable = -1;
unsigned char temp_register_rtc[2];

volatile unsigned int periodical_tasks_TEST_SETTINGS_PRT = false;
volatile unsigned int periodical_tasks_TEST_SETTINGS_BS = false;
volatile unsigned int periodical_tasks_TEST_USTUVANNJA = false;
volatile unsigned int periodical_tasks_TEST_TRG_FUNC = false;
volatile unsigned int periodical_tasks_TEST_INFO_REJESTRATOR_AR = false;
volatile unsigned int periodical_tasks_TEST_INFO_REJESTRATOR_DR = false;
volatile unsigned int periodical_tasks_TEST_INFO_REJESTRATOR_PR_ERR = false;

unsigned int diagnostyka[2] = {0, 0};

unsigned char rtc_time[8]; 
unsigned char rtc_time_copy[8]; 
unsigned char rtc_calibration;
unsigned char rtc_calibration_copy;
unsigned int copying_time = 0;
unsigned char rtc_time_edit[8]; 
unsigned char rtc_calibration_edit;
unsigned int copy_register8_RTC;

unsigned char crc_ustuvannja;
unsigned int ustuvannja[NUMBER_CANALS];
int phi_ustuvannja[NUMBER_CANALS];
unsigned int ustuvannja_P[3], ustuvannja_Q[3];

CfgTblDsc eeprom_prt_tbl;
unsigned char crc_settings_prt;
AuxCfgTbl1Dsc eeprom_bs_settings_tbl;
unsigned char modbus_address;
unsigned char crc_settings_bs;

unsigned int state_signal_outputs = 0;
unsigned int state_trigger_leds = 0;

unsigned int trigger_active_functions[N_TMP]  = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

//Serial DataFlash
unsigned int AR_DR = _DF_NONE;

unsigned int status_register_df_ar;
unsigned int address_read_write_ar;
unsigned int number_bytes_read_write_ar;
DDR2_B1_2_DATA unsigned int buffer_serial_DataFlash_read_write_ar[SIZE_BUFFER_SERIAL_DATAFLASH_READ_WRITE_AR];

unsigned int status_register_df_dr;
unsigned int address_read_write_dr;
unsigned int number_bytes_read_write_dr;
DDR2_B1_2_DATA unsigned int buffer_serial_DataFlash_read_write_dr[SIZE_BUFFER_SERIAL_DATAFLASH_READ_WRITE_DR];

__INFO_REJESTRATOR info_rejestrator_ar;
unsigned char crc_info_rejestrator_ar;

__TEMP_STRUCTURE EepromDRecDesc;
unsigned char crc_info_rejestrator_dr;

unsigned char crc_info_rejestrator_pr_err;

unsigned int control_ar_taskes = 0;
DDR2_B1_2_DATA unsigned char table_data_ar[NUMBER_DATA_BLOCKS + 1];

#endif
