#ifndef __DIAGNOSTYKA_H
#define __DIAGNOSTYKA_H

enum _error_id {
ERROR_VREF_ADC1_TEST_BIT = 0,
ERROR_VDD_ADC1_TEST_BIT,
ERROR_VREF_ADC1_TEST_COARSE_BIT,
ERROR_VDD_ADC1_TEST_COARSE_BIT,

ERROR_VREF_ADC2_TEST_BIT,
ERROR_VDD_ADC2_TEST_BIT,
ERROR_VREF_ADC2_TEST_COARSE_BIT,
ERROR_VDD_ADC2_TEST_COARSE_BIT,

ERROR_VREF_ADC3_TEST_BIT,
ERROR_VDD_ADC3_TEST_BIT,
ERROR_VREF_ADC3_TEST_COARSE_BIT,
ERROR_VDD_ADC3_TEST_COARSE_BIT,

ERROR_EXTERNAL_SRAM_BIT,
ERROR_EXTERNAL_FLASH_MEMORY_BIT
};

#endif
