#ifndef __DIAGNOSTYKA_BM_H
#define __DIAGNOSTYKA_BM_H

enum _error_bm_id {
ERROR_BV_VREF_ADC1_TEST_BIT = 0,
ERROR_BV_VDD_ADC1_TEST_BIT,
ERROR_BV_VREF_ADC1_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC1_TEST_COARSE_BIT,

ERROR_BV_VREF_ADC2_TEST_BIT,
ERROR_BV_VDD_ADC2_TEST_BIT,
ERROR_BV_VREF_ADC2_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC2_TEST_COARSE_BIT,

ERROR_BV_VREF_ADC3_TEST_BIT,
ERROR_BV_VDD_ADC3_TEST_BIT,
ERROR_BV_VREF_ADC3_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC3_TEST_COARSE_BIT,

ERROR_BV_EXTERNAL_SRAM_BIT,
ERROR_BV_EXTERNAL_FLASH_MEMORY_BIT,

ERROR_BV_START_VIA_I2C_BIT,
ERROR_BV_START_READING_I2C_BIT,
ERROR_BV_SETTINGS_EEPROM_BIT,
ERROR_BV_SETTINGS_EEPROM_EMPTY_BIT,
ERROR_BV_SETTINGS_EEPROM_COMPARISON_BIT,
ERROR_BV_SETTINGS_EEPROM_CONTROL_BIT,
ERROR_BV_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT,
ERROR_BV_USTUVANNJA_EEPROM_BIT,
ERROR_BV_USTUVANNJA_EEPROM_EMPTY_BIT,
ERROR_BV_USTUVANNJA_EEPROM_COMPARISON_BIT,
ERROR_BV_USTUVANNJA_EEPROM_CONTROL_BIT,
ERROR_BV_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT,
ERROR_BV_POWER_EEPROM_BIT,
ERROR_BV_POWER_EEPROM_EMPTY_BIT,
ERROR_BV_POWER_EEPROM_COMPARISON_BIT,
ERROR_BV_POWER_EEPROM_CONTROL_BIT,

ERROR_OSCYLOJRAPH_OVERFLOW

};
enum BmFatalEror {

ERROR_BM_VREF_ADC1_TEST_BIT                      = ERROR_BV_VREF_ADC1_TEST_BIT ,

ERROR_BM_VDD_ADC1_TEST_BIT                       = ERROR_BV_VDD_ADC1_TEST_BIT  ,
ERROR_BM_VREF_ADC1_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC1_TEST_COARSE_BIT,
ERROR_BM_VDD_ADC1_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC1_TEST_COARSE_BIT ,
                                                  
ERROR_BM_VREF_ADC2_TEST_BIT                      = ERROR_BV_VREF_ADC2_TEST_BIT               ,
ERROR_BM_VDD_ADC2_TEST_BIT                       = ERROR_BV_VDD_ADC2_TEST_BIT                ,
ERROR_BM_VREF_ADC2_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC2_TEST_COARSE_BIT        ,
ERROR_BM_VDD_ADC2_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC2_TEST_COARSE_BIT         ,
                                                  
ERROR_BM_VREF_ADC3_TEST_BIT                      = ERROR_BV_VREF_ADC3_TEST_BIT               ,
ERROR_BM_VDD_ADC3_TEST_BIT                       = ERROR_BV_VDD_ADC3_TEST_BIT                ,
ERROR_BM_VREF_ADC3_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC3_TEST_COARSE_BIT        ,
ERROR_BM_VDD_ADC3_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC3_TEST_COARSE_BIT         ,
                                                  
ERROR_BM_EXTERNAL_SRAM_BIT                       = ERROR_BV_EXTERNAL_SRAM_BIT                         ,
ERROR_BM_EXTERNAL_FLASH_MEMORY_BIT               = ERROR_BV_EXTERNAL_FLASH_MEMORY_BIT                 ,
                                                  
ERROR_BM_START_VIA_I2C_BIT                        =  ERROR_BV_START_VIA_I2C_BIT                       ,
ERROR_BM_START_READING_I2C_BIT                    =  ERROR_BV_START_READING_I2C_BIT                   ,
ERROR_BM_SETTINGS_EEPROM_BIT                      =  ERROR_BV_SETTINGS_EEPROM_BIT                     ,
ERROR_BM_SETTINGS_EEPROM_EMPTY_BIT                =  ERROR_BV_SETTINGS_EEPROM_EMPTY_BIT               ,
ERROR_BM_SETTINGS_EEPROM_COMPARISON_BIT           =  ERROR_BV_SETTINGS_EEPROM_COMPARISON_BIT          ,
ERROR_BM_SETTINGS_EEPROM_CONTROL_BIT              =  ERROR_BV_SETTINGS_EEPROM_CONTROL_BIT             ,
ERROR_BM_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT       =  ERROR_BV_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT      ,
ERROR_BM_USTUVANNJA_EEPROM_BIT                    =  ERROR_BV_USTUVANNJA_EEPROM_BIT                   ,
ERROR_BM_USTUVANNJA_EEPROM_EMPTY_BIT              =  ERROR_BV_USTUVANNJA_EEPROM_EMPTY_BIT             ,
ERROR_BM_USTUVANNJA_EEPROM_COMPARISON_BIT         =  ERROR_BV_USTUVANNJA_EEPROM_COMPARISON_BIT        ,
ERROR_BM_USTUVANNJA_EEPROM_CONTROL_BIT            =  ERROR_BV_USTUVANNJA_EEPROM_CONTROL_BIT           ,
ERROR_BM_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT =  ERROR_BV_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT,
ERROR_BM_POWER_EEPROM_BIT                         =  ERROR_BV_POWER_EEPROM_BIT                        ,
ERROR_BM_POWER_EEPROM_EMPTY_BIT                   =  ERROR_BV_POWER_EEPROM_EMPTY_BIT                  ,
ERROR_BM_POWER_EEPROM_COMPARISON_BIT              =  ERROR_BV_POWER_EEPROM_COMPARISON_BIT             ,
ERROR_BM_POWER_EEPROM_CONTROL_BIT                 =  ERROR_BV_POWER_EEPROM_CONTROL_BIT                 

};





#endif
