#ifndef __DIAGNOSTYKA_BM_H
#define __DIAGNOSTYKA_BM_H

enum _error_bm_id {
ERROR_BV_VREF_ADC1_TEST_BIT = 0,
ERROR_BV_VDD_ADC1_TEST_BIT,
ERROR_BV_VREF_ADC1_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC1_TEST_COARSE_BIT,

ERROR_BV_VREF_ADC2_TEST_BIT,
ERROR_BV_VDD_ADC2_TEST_BIT,
ERROR_BV_VREF_ADC2_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC2_TEST_COARSE_BIT,

ERROR_BV_VREF_ADC3_TEST_BIT,
ERROR_BV_VDD_ADC3_TEST_BIT,
ERROR_BV_VREF_ADC3_TEST_COARSE_BIT,
ERROR_BV_VDD_ADC3_TEST_COARSE_BIT,

ERROR_BV_EXTERNAL_SRAM_BIT,
ERROR_BV_EXTERNAL_FLASH_MEMORY_BIT,

ERROR_BV_START_VIA_I2C_BIT,
ERROR_BV_START_READING_I2C_BIT,
ERROR_BV_SETTINGS_EEPROM_BIT,
ERROR_BV_SETTINGS_EEPROM_EMPTY_BIT,
ERROR_BV_SETTINGS_EEPROM_COMPARISON_BIT,
ERROR_BV_SETTINGS_EEPROM_CONTROL_BIT,
ERROR_BV_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT,
ERROR_BV_USTUVANNJA_EEPROM_BIT,
ERROR_BV_USTUVANNJA_EEPROM_EMPTY_BIT,
ERROR_BV_USTUVANNJA_EEPROM_COMPARISON_BIT,
ERROR_BV_USTUVANNJA_EEPROM_CONTROL_BIT,
ERROR_BV_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT,
ERROR_BV_POWER_EEPROM_BIT,
ERROR_BV_POWER_EEPROM_EMPTY_BIT,
ERROR_BV_POWER_EEPROM_COMPARISON_BIT,
ERROR_BV_POWER_EEPROM_CONTROL_BIT,

ERROR_OSCYLOJRAPH_OVERFLOW

};
enum BmFatalEror {

ERROR_BM_VREF_ADC1_TEST_BIT                      = ERROR_BV_VREF_ADC1_TEST_BIT ,

ERROR_BM_VDD_ADC1_TEST_BIT                       = ERROR_BV_VDD_ADC1_TEST_BIT  ,
ERROR_BM_VREF_ADC1_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC1_TEST_COARSE_BIT,
ERROR_BM_VDD_ADC1_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC1_TEST_COARSE_BIT ,
                                                  
ERROR_BM_VREF_ADC2_TEST_BIT                      = ERROR_BV_VREF_ADC2_TEST_BIT               ,
ERROR_BM_VDD_ADC2_TEST_BIT                       = ERROR_BV_VDD_ADC2_TEST_BIT                ,
ERROR_BM_VREF_ADC2_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC2_TEST_COARSE_BIT        ,
ERROR_BM_VDD_ADC2_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC2_TEST_COARSE_BIT         ,
                                                  
ERROR_BM_VREF_ADC3_TEST_BIT                      = ERROR_BV_VREF_ADC3_TEST_BIT               ,
ERROR_BM_VDD_ADC3_TEST_BIT                       = ERROR_BV_VDD_ADC3_TEST_BIT                ,
ERROR_BM_VREF_ADC3_TEST_COARSE_BIT               = ERROR_BV_VREF_ADC3_TEST_COARSE_BIT        ,
ERROR_BM_VDD_ADC3_TEST_COARSE_BIT                = ERROR_BV_VDD_ADC3_TEST_COARSE_BIT         ,
                                                  
ERROR_BM_EXTERNAL_SRAM_BIT                       = ERROR_BV_EXTERNAL_SRAM_BIT                         ,
ERROR_BM_EXTERNAL_FLASH_MEMORY_BIT               = ERROR_BV_EXTERNAL_FLASH_MEMORY_BIT                 ,
                                                  
ERROR_BM_START_VIA_I2C_BIT                        =  ERROR_BV_START_VIA_I2C_BIT                       ,
ERROR_BM_START_READING_I2C_BIT                    =  ERROR_BV_START_READING_I2C_BIT                   ,
ERROR_BM_SETTINGS_EEPROM_BIT                      =  ERROR_BV_SETTINGS_EEPROM_BIT                     ,
ERROR_BM_SETTINGS_EEPROM_EMPTY_BIT                =  ERROR_BV_SETTINGS_EEPROM_EMPTY_BIT               ,
ERROR_BM_SETTINGS_EEPROM_COMPARISON_BIT           =  ERROR_BV_SETTINGS_EEPROM_COMPARISON_BIT          ,
ERROR_BM_SETTINGS_EEPROM_CONTROL_BIT              =  ERROR_BV_SETTINGS_EEPROM_CONTROL_BIT             ,
ERROR_BM_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT       =  ERROR_BV_SETTINGS_EEPROM_DEVICE_ID_FAIL_BIT      ,
ERROR_BM_USTUVANNJA_EEPROM_BIT                    =  ERROR_BV_USTUVANNJA_EEPROM_BIT                   ,
ERROR_BM_USTUVANNJA_EEPROM_EMPTY_BIT              =  ERROR_BV_USTUVANNJA_EEPROM_EMPTY_BIT             ,
ERROR_BM_USTUVANNJA_EEPROM_COMPARISON_BIT         =  ERROR_BV_USTUVANNJA_EEPROM_COMPARISON_BIT        ,
ERROR_BM_USTUVANNJA_EEPROM_CONTROL_BIT            =  ERROR_BV_USTUVANNJA_EEPROM_CONTROL_BIT           ,
ERROR_BM_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT =  ERROR_BV_USTUVANNJA_EEPROM_ADJUSTMENT_ID_FAIL_BIT,
ERROR_BM_POWER_EEPROM_BIT                         =  ERROR_BV_POWER_EEPROM_BIT                        ,
ERROR_BM_POWER_EEPROM_EMPTY_BIT                   =  ERROR_BV_POWER_EEPROM_EMPTY_BIT                  ,
ERROR_BM_POWER_EEPROM_COMPARISON_BIT              =  ERROR_BV_POWER_EEPROM_COMPARISON_BIT             ,
ERROR_BM_POWER_EEPROM_CONTROL_BIT                 =  ERROR_BV_POWER_EEPROM_CONTROL_BIT                ,

ERROR_BM_FATAL_EROR_LAST_BIT
};

//#ifndef __TYPE_DEFINITION_BS_H

//#define SIZE_BM_RAM_PRG_EVT_UNN (  (( (ERROR_BM_FATAL_EROR_LAST_BIT )>>2)<<2) + (4*(1&&( (ERROR_BM_FATAL_EROR_LAST_BIT ))&3))    )
#define SIZE_BM_RAM_PRG_EVT_UNN (  (( (ERROR_BM_FATAL_EROR_LAST_BIT )>>3)) + (4*(1&&( (ERROR_BM_FATAL_EROR_LAST_BIT ))&3))    )

//#endif 

typedef struct tag_BmRamPrgEvtDsc
{
	union 
	{
		char   chArBmPrgEvts  [ SIZE_BM_RAM_PRG_EVT_UNN];
		short  shArBmPrgEvts  [ (SIZE_BM_RAM_PRG_EVT_UNN>>1)];
	    long   lArBmPrgEvts   [ (SIZE_BM_RAM_PRG_EVT_UNN>>2)];
		
	}UNBmRamPrgEvts;
	//long Additio Var if Need;
}BmRamPrgEvtDsc;




#endif
